## 31-07-2022

Pandas, Mysql, Mongodb

##### Task 1 - Fitbit Dataset

1. Read this dataset in pandas , mysql and mongodb.
2. While creating a table in mysql dont use manual approach to create it  ,always use a automation to create a table in mysql. </br>
        **hint - use csvkit library to automate this task and to load a data in bulk in your mysql </br>
3. Convert all the dates available in dataset to timestamp format in pandas and in sql you to convert it in date format.
4. Find out in this data that how many unique id's we have.
5. Which id is one of the active id that you have in whole dataset.
6. How many of them have not logged there activity find out in terms of number of ids.
7. Find out who is the laziest person id that we have in dataset. 
8. Explore over an internet that how much calories burn is required for a healthy person and find out how many healthy person we have in our dataset.
9. How many person are not a regular person with respect to activity try to find out those.
10. Who is the third most active person in this dataset find out those in pandas and in sql both. 
11. Who is the 5th most laziest person avilable in dataset find it out. 
12. What is a total acumulative calories burn for a person find out.

##### Task 2 - Superstore_USA

1. Load this data in sql and in pandas with a relation in sql. 
2. While loading this data you dont have to create a table manually you can use any automated approach to create a table and load a data in bulk in table.
3. Find out how return that we have recived and with a product id.
4. Try to join order and return data both in sql and pandas. 
5. Try to find out how many unique customer that we have.
6. Try to find out in how many regions we are selling a product and who is a manager for a respective region.
7. Find out how many different differnet shipement mode that we have and what is a percentage usablity of all the shipment mode with respect to dataset.
8. Create a new coulmn and try to find our a diffrence between order date and shipment date.
9. Based on question number 8 find out for which order id we have shipment duration more than 10 days.
10. Try to find out a list of a returned order which sihpment duration was more then 15 days and find out that region manager as well.
11. Gorup by region and find out which region is more profitable.
12. Try to find out overall in which country we are giving more discount. 
13. Give me a list of unique postal code.
14. Which customer segement is more profitalble find it out.
15. Try to find out the 10th most loss making product catagory. 
16. Try to find out 10 top product with highest margins.

submit your git link for the same 
 
you have to submit this task by next Friday 5th 11PM IST  to respective mail id 
sudhanshu@ineuron.ai , sunny.savita@ineuron.ai

</br> </br> </br> </br>

### Task 1 - Fitbit Dataset

1. Read this dataset in pandas , mysql and mongodb.
2. While creating a table in mysql dont use manual approach to create it  ,always use a automation to create a table in mysql. </br>
        **hint - use csvkit library to automate this task and to load a data in bulk in your mysql </br>
3. Convert all the dates available in dataset to timestamp format in pandas and in sql you to convert it in date format.
4. Find out in this data that how many unique id's we have.
5. Which id is one of the active id that you have in whole dataset.
6. How many of them have not logged there activity find out in terms of number of ids.
7. Find out who is the laziest person id that we have in dataset. 
8. Explore over an internet that how much calories burn is required for a healthy person and find out how many healthy person we have in our dataset.
9. How many person are not a regular person with respect to activity try to find out those.
10. Who is the third most active person in this dataset find out those in pandas and in sql both. 
11. Who is the 5th most laziest person avilable in dataset find it out. 
12. What is a total acumulative calories burn for a person find out.

### 1. Read this dataset in pandas , mysql and mongodb.

#### Pandas

In [1]:
import pandas as pd

In [2]:
fitbit = pd.read_csv("G:\Study\ineuron\Live coding in lectures\Pandas\data fsds -20220726T060614Z-001\data fsds\FitBit data.csv")
fitbit

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,3/25/2016,11004,7.110000,7.110000,0.0,2.57,0.46,4.07,0.00,33,12,205,804,1819
1,1503960366,3/26/2016,17609,11.550000,11.550000,0.0,6.92,0.73,3.91,0.00,89,17,274,588,2154
2,1503960366,3/27/2016,12736,8.530000,8.530000,0.0,4.66,0.16,3.71,0.00,56,5,268,605,1944
3,1503960366,3/28/2016,13231,8.930000,8.930000,0.0,3.19,0.79,4.95,0.00,39,20,224,1080,1932
4,1503960366,3/29/2016,12041,7.850000,7.850000,0.0,2.16,1.09,4.61,0.00,28,28,243,763,1886
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,8877689391,4/8/2016,23014,20.389999,20.389999,0.0,11.10,0.63,8.62,0.00,70,29,359,982,4196
453,8877689391,4/9/2016,16470,8.070000,8.070000,0.0,0.00,0.02,8.02,0.00,90,9,289,1052,3841
454,8877689391,4/10/2016,28497,27.530001,27.530001,0.0,21.92,1.12,4.46,0.00,128,46,211,1055,4526
455,8877689391,4/11/2016,10622,8.060000,8.060000,0.0,1.47,0.15,6.37,0.01,18,7,225,1190,2820
456,8877689391,4/12/2016,2350,1.780000,1.780000,0.0,0.00,0.00,1.78,0.00,0,0,58,531,938

#### MongoDB

In [3]:
fitbit_json = fitbit.to_json("fitbit_json.json")

In [4]:
import pymongo
import json

In [5]:
from MongoDB_login import *
client = pymongo.MongoClient(f"mongodb+srv://{user_name}:{mdb_password}.ku1bjvf.mongodb.net/?retryWrites=true&w=majority")
db = client.test
print(db)

database = client['task31072022']
collection = database['fitbit']

with open(r"G:\Study\ineuron\Live lecture resource\fitbit_json.json") as f:
    f_data = json.load(f)
    
collection.insert_one(f_data)

Database(MongoClient(host=['ac-seysk7d-shard-00-00.ku1bjvf.mongodb.net:27017', 'ac-seysk7d-shard-00-01.ku1bjvf.mongodb.net:27017', 'ac-seysk7d-shard-00-02.ku1bjvf.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', authsource='admin', replicaset='atlas-jtsuo7-shard-0', tls=True), 'test')

In [6]:
x = collection.find()
for data in x:
    print(data)

{'_id': ObjectId('62ea1b085d8eddcbb59f7278'), 'Id': {'0': 1503960366, '1': 1503960366, '2': 1503960366, '3': 1503960366, '4': 1503960366, '5': 1503960366, '6': 1503960366, '7': 1503960366, '8': 1503960366, '9': 1503960366, '10': 1503960366, '11': 1503960366, '12': 1503960366, '13': 1503960366, '14': 1503960366, '15': 1503960366, '16': 1503960366, '17': 1503960366, '18': 1503960366, '19': 1624580081, '20': 1624580081, '21': 1624580081, '22': 1624580081, '23': 1624580081, '24': 1624580081, '25': 1624580081, '26': 1624580081, '27': 1624580081, '28': 1624580081, '29': 1624580081, '30': 1624580081, '31': 1624580081, '32': 1624580081, '33': 1624580081, '34': 1624580081, '35': 1624580081, '36': 1624580081, '37': 1624580081, '38': 1644430081, '39': 1644430081, '40': 1644430081, '41': 1644430081, '42': 1644430081, '43': 1644430081, '44': 1644430081, '45': 1644430081, '46': 1644430081, '47': 1644430081, '48': 1844505072, '49': 1844505072, '50': 1844505072, '51': 1844505072, '52': 1844505072, '53': 1844505072, '54': 1844505072, '55': 1844505072, '56': 1844505072, '57': 1844505072, '58': 1844505072, '59': 1844505072, '60': 1927972279, '61': 1927972279, '62': 1927972279, '63': 1927972279, '64': 1927972279, '65': 1927972279, '66': 1927972279, '67': 1927972279, '68': 1927972279, '69': 1927972279, '70': 1927972279, '71': 1927972279, '72': 2022484408, '73': 2022484408, '74': 2022484408, '75': 2022484408, '76': 2022484408, '77': 2022484408, '78': 2022484408, '79': 2022484408, '80': 2022484408, '81': 2022484408, '82': 2022484408, '83': 2022484408, '84': 2026352035, '85': 2026352035, '86': 2026352035, '87': 2026352035, '88': 2026352035, '89': 2026352035, '90': 2026352035, '91': 2026352035, '92': 2026352035, '93': 2026352035, '94': 2026352035, '95': 2026352035, '96': 2320127002, '97': 2320127002, '98': 2320127002, '99': 2320127002, '100': 2320127002, '101': 2320127002, '102': 2320127002, '103': 2320127002, '104': 2320127002, '105': 2320127002, '106': 2320127002, '107': 2320127002, '108': 2347167796, '109': 2347167796, '110': 2347167796, '111': 2347167796, '112': 2347167796, '113': 2347167796, '114': 2347167796, '115': 2347167796, '116': 2347167796, '117': 2347167796, '118': 2347167796, '119': 2347167796, '120': 2347167796, '121': 2347167796, '122': 2347167796, '123': 2873212765, '124': 2873212765, '125': 2873212765, '126': 2873212765, '127': 2873212765, '128': 2873212765, '129': 2873212765, '130': 2873212765, '131': 2873212765, '132': 2873212765, '133': 2873212765, '134': 2873212765, '135': 2891001357, '136': 2891001357, '137': 2891001357, '138': 2891001357, '139': 2891001357, '140': 2891001357, '141': 2891001357, '142': 2891001357, '143': 3372868164, '144': 3372868164, '145': 3372868164, '146': 3372868164, '147': 3372868164, '148': 3372868164, '149': 3372868164, '150': 3372868164, '151': 3372868164, '152': 3372868164, '153': 3977333714, '154': 3977333714, '155': 3977333714, '156': 3977333714, '157': 3977333714, '158': 3977333714, '159': 3977333714, '160': 3977333714, '161': 3977333714, '162': 3977333714, '163': 3977333714, '164': 3977333714, '165': 4020332650, '166': 4020332650, '167': 4020332650, '168': 4020332650, '169': 4020332650, '170': 4020332650, '171': 4020332650, '172': 4020332650, '173': 4020332650, '174': 4020332650, '175': 4020332650, '176': 4020332650, '177': 4020332650, '178': 4020332650, '179': 4020332650, '180': 4020332650, '181': 4020332650, '182': 4020332650, '183': 4020332650, '184': 4020332650, '185': 4020332650, '186': 4020332650, '187': 4020332650, '188': 4020332650, '189': 4020332650, '190': 4020332650, '191': 4020332650, '192': 4020332650, '193': 4020332650, '194': 4020332650, '195': 4020332650, '196': 4020332650, '197': 4057192912, '198': 4057192912, '199': 4057192912, '200': 4057192912, '201': 4057192912, '202': 4057192912, '203': 4057192912, '204': 4057192912, '205': 4057192912, '206': 4057192912, '207': 4057192912, '208': 4057192912, '209': 4057192912, '210': 4057192912, '211': 4057192912, '212': 4057192912, '213': 4057192912, '214': 4057192912, '215': 4057192912, '216': 4057192912, '217': 4057192912, '218': 4057192912, '219': 4057192912, '220': 4057192912, '221': 4057192912, '222': 4057192912, '223': 4057192912, '224': 4057192912, '225': 4057192912, '226': 4057192912, '227': 4057192912, '228': 4057192912, '229': 4319703577, '230': 4319703577, '231': 4319703577, '232': 4319703577, '233': 4319703577, '234': 4319703577, '235': 4319703577, '236': 4319703577, '237': 4319703577, '238': 4319703577, '239': 4319703577, '240': 4319703577, '241': 4388161847, '242': 4388161847, '243': 4388161847, '244': 4388161847, '245': 4388161847, '246': 4388161847, '247': 4388161847, '248': 4388161847, '249': 4445114986, '250': 4445114986, '251': 4445114986, '252': 4445114986, '253': 4445114986, '254': 4445114986, '255': 4445114986, '256': 4445114986, '257': 4445114986, '258': 4445114986, '259': 4445114986, '260': 4445114986, '261': 4445114986, '262': 4445114986, '263': 4445114986, '264': 4558609924, '265': 4558609924, '266': 4558609924, '267': 4558609924, '268': 4558609924, '269': 4558609924, '270': 4558609924, '271': 4558609924, '272': 4558609924, '273': 4558609924, '274': 4558609924, '275': 4558609924, '276': 4702921684, '277': 4702921684, '278': 4702921684, '279': 4702921684, '280': 4702921684, '281': 4702921684, '282': 4702921684, '283': 4702921684, '284': 4702921684, '285': 4702921684, '286': 4702921684, '287': 4702921684, '288': 4702921684, '289': 4702921684, '290': 4702921684, '291': 5553957443, '292': 5553957443, '293': 5553957443, '294': 5553957443, '295': 5553957443, '296': 5553957443, '297': 5553957443, '298': 5553957443, '299': 5553957443, '300': 5553957443, '301': 5553957443, '302': 5553957443, '303': 5577150313, '304': 5577150313, '305': 5577150313, '306': 5577150313, '307': 5577150313, '308': 5577150313, '309': 5577150313, '310': 5577150313, '311': 5577150313, '312': 5577150313, '313': 5577150313, '314': 6117666160, '315': 6117666160, '316': 6117666160, '317': 6117666160, '318': 6117666160, '319': 6117666160, '320': 6117666160, '321': 6117666160, '322': 6117666160, '323': 6117666160, '324': 6290855005, '325': 6290855005, '326': 6290855005, '327': 6290855005, '328': 6290855005, '329': 6290855005, '330': 6290855005, '331': 6290855005, '332': 6290855005, '333': 6290855005, '334': 6391747486, '335': 6391747486, '336': 6391747486, '337': 6391747486, '338': 6391747486, '339': 6391747486, '340': 6391747486, '341': 6391747486, '342': 6391747486, '343': 6775888955, '344': 6775888955, '345': 6775888955, '346': 6775888955, '347': 6775888955, '348': 6775888955, '349': 6775888955, '350': 6775888955, '351': 6775888955, '352': 6962181067, '353': 6962181067, '354': 6962181067, '355': 6962181067, '356': 6962181067, '357': 6962181067, '358': 6962181067, '359': 6962181067, '360': 6962181067, '361': 6962181067, '362': 6962181067, '363': 6962181067, '364': 6962181067, '365': 6962181067, '366': 7007744171, '367': 7007744171, '368': 7007744171, '369': 7007744171, '370': 7007744171, '371': 7007744171, '372': 7007744171, '373': 7007744171, '374': 7007744171, '375': 7007744171, '376': 7007744171, '377': 7007744171, '378': 7086361926, '379': 7086361926, '380': 7086361926, '381': 7086361926, '382': 7086361926, '383': 7086361926, '384': 7086361926, '385': 7086361926, '386': 7086361926, '387': 7086361926, '388': 7086361926, '389': 7086361926, '390': 8053475328, '391': 8053475328, '392': 8053475328, '393': 8053475328, '394': 8053475328, '395': 8053475328, '396': 8053475328, '397': 8053475328, '398': 8053475328, '399': 8053475328, '400': 8053475328, '401': 8253242879, '402': 8253242879, '403': 8253242879, '404': 8253242879, '405': 8253242879, '406': 8253242879, '407': 8253242879, '408': 8253242879, '409': 8253242879, '410': 8253242879, '411': 8253242879, '412': 8253242879, '413': 8378563200, '414': 8378563200, '415': 8378563200, '416': 8378563200, '417': 8378563200, '418': 8378563200, '419': 8378563200, '420': 8378563200, '421': 8378563200, '422': 8378563200, '423': 8378563200, '424': 8378563200, '425': 8583815059, '426': 8583815059, '427': 8583815059, '428': 8583815059, '429': 8583815059, '430': 8583815059, '431': 8583815059, '432': 8583815059, '433': 8792009665, '434': 8792009665, '435': 8792009665, '436': 8792009665, '437': 8792009665, '438': 8792009665, '439': 8792009665, '440': 8792009665, '441': 8792009665, '442': 8792009665, '443': 8792009665, '444': 8792009665, '445': 8877689391, '446': 8877689391, '447': 8877689391, '448': 8877689391, '449': 8877689391, '450': 8877689391, '451': 8877689391, '452': 8877689391, '453': 8877689391, '454': 8877689391, '455': 8877689391, '456': 8877689391}, 'ActivityDate': {'0': '3/25/2016', '1': '3/26/2016', '2': '3/27/2016', '3': '3/28/2016', '4': '3/29/2016', '5': '3/30/2016', '6': '3/31/2016', '7': '4/1/2016', '8': '4/2/2016', '9': '4/3/2016', '10': '4/4/2016', '11': '4/5/2016', '12': '4/6/2016', '13': '4/7/2016', '14': '4/8/2016', '15': '4/9/2016', '16': '4/10/2016', '17': '4/11/2016', '18': '4/12/2016', '19': '3/25/2016', '20': '3/26/2016', '21': '3/27/2016', '22': '3/28/2016', '23': '3/29/2016', '24': '3/30/2016', '25': '3/31/2016', '26': '4/1/2016', '27': '4/2/2016', '28': '4/3/2016', '29': '4/4/2016', '30': '4/5/2016', '31': '4/6/2016', '32': '4/7/2016', '33': '4/8/2016', '34': '4/9/2016', '35': '4/10/2016', '36': '4/11/2016', '37': '4/12/2016', '38': '4/1/2016', '39': '4/2/2016', '40': '4/3/2016', '41': '4/4/2016', '42': '4/5/2016', '43': '4/6/2016', '44': '4/7/2016', '45': '4/8/2016', '46': '4/9/2016', '47': '4/10/2016', '48': '4/1/2016', '49': '4/2/2016', '50': '4/3/2016', '51': '4/4/2016', '52': '4/5/2016', '53': '4/6/2016', '54': '4/7/2016', '55': '4/8/2016', '56': '4/9/2016', '57': '4/10/2016', '58': '4/11/2016', '59': '4/12/2016', '60': '4/1/2016', '61': '4/2/2016', '62': '4/3/2016', '63': '4/4/2016', '64': '4/5/2016', '65': '4/6/2016', '66': '4/7/2016', '67': '4/8/2016', '68': '4/9/2016', '69': '4/10/2016', '70': '4/11/2016', '71': '4/12/2016', '72': '4/1/2016', '73': '4/2/2016', '74': '4/3/2016', '75': '4/4/2016', '76': '4/5/2016', '77': '4/6/2016', '78': '4/7/2016', '79': '4/8/2016', '80': '4/9/2016', '81': '4/10/2016', '82': '4/11/2016', '83': '4/12/2016', '84': '4/1/2016', '85': '4/2/2016', '86': '4/3/2016', '87': '4/4/2016', '88': '4/5/2016', '89': '4/6/2016', '90': '4/7/2016', '91': '4/8/2016', '92': '4/9/2016', '93': '4/10/2016', '94': '4/11/2016', '95': '4/12/2016', '96': '4/1/2016', '97': '4/2/2016', '98': '4/3/2016', '99': '4/4/2016', '100': '4/5/2016', '101': '4/6/2016', '102': '4/7/2016', '103': '4/8/2016', '104': '4/9/2016', '105': '4/10/2016', '106': '4/11/2016', '107': '4/12/2016', '108': '3/29/2016', '109': '3/30/2016', '110': '3/31/2016', '111': '4/1/2016', '112': '4/2/2016', '113': '4/3/2016', '114': '4/4/2016', '115': '4/5/2016', '116': '4/6/2016', '117': '4/7/2016', '118': '4/8/2016', '119': '4/9/2016', '120': '4/10/2016', '121': '4/11/2016', '122': '4/12/2016', '123': '4/1/2016', '124': '4/2/2016', '125': '4/3/2016', '126': '4/4/2016', '127': '4/5/2016', '128': '4/6/2016', '129': '4/7/2016', '130': '4/8/2016', '131': '4/9/2016', '132': '4/10/2016', '133': '4/11/2016', '134': '4/12/2016', '135': '3/29/2016', '136': '3/30/2016', '137': '3/31/2016', '138': '4/1/2016', '139': '4/2/2016', '140': '4/3/2016', '141': '4/4/2016', '142': '4/5/2016', '143': '4/1/2016', '144': '4/2/2016', '145': '4/3/2016', '146': '4/4/2016', '147': '4/5/2016', '148': '4/6/2016', '149': '4/7/2016', '150': '4/8/2016', '151': '4/9/2016', '152': '4/10/2016', '153': '4/1/2016', '154': '4/2/2016', '155': '4/3/2016', '156': '4/4/2016', '157': '4/5/2016', '158': '4/6/2016', '159': '4/7/2016', '160': '4/8/2016', '161': '4/9/2016', '162': '4/10/2016', '163': '4/11/2016', '164': '4/12/2016', '165': '3/12/2016', '166': '3/13/2016', '167': '3/14/2016', '168': '3/15/2016', '169': '3/16/2016', '170': '3/17/2016', '171': '3/18/2016', '172': '3/19/2016', '173': '3/20/2016', '174': '3/21/2016', '175': '3/22/2016', '176': '3/23/2016', '177': '3/24/2016', '178': '3/25/2016', '179': '3/26/2016', '180': '3/27/2016', '181': '3/28/2016', '182': '3/29/2016', '183': '3/30/2016', '184': '3/31/2016', '185': '4/1/2016', '186': '4/2/2016', '187': '4/3/2016', '188': '4/4/2016', '189': '4/5/2016', '190': '4/6/2016', '191': '4/7/2016', '192': '4/8/2016', '193': '4/9/2016', '194': '4/10/2016', '195': '4/11/2016', '196': '4/12/2016', '197': '3/12/2016', '198': '3/13/2016', '199': '3/14/2016', '200': '3/15/2016', '201': '3/16/2016', '202': '3/17/2016', '203': '3/18/2016', '204': '3/19/2016', '205': '3/20/2016', '206': '3/21/2016', '207': '3/22/2016', '208': '3/23/2016', '209': '3/24/2016', '210': '3/25/2016', '211': '3/26/2016', '212': '3/27/2016', '213': '3/28/2016', '214': '3/29/2016', '215': '3/30/2016', '216': '3/31/2016', '217': '4/1/2016', '218': '4/2/2016', '219': '4/3/2016', '220': '4/4/2016', '221': '4/5/2016', '222': '4/6/2016', '223': '4/7/2016', '224': '4/8/2016', '225': '4/9/2016', '226': '4/10/2016', '227': '4/11/2016', '228': '4/12/2016', '229': '3/29/2016', '230': '3/30/2016', '231': '3/31/2016', '232': '4/1/2016', '233': '4/2/2016', '234': '4/3/2016', '235': '4/4/2016', '236': '4/5/2016', '237': '4/6/2016', '238': '4/7/2016', '239': '4/8/2016', '240': '4/9/2016', '241': '3/29/2016', '242': '3/30/2016', '243': '3/31/2016', '244': '4/1/2016', '245': '4/2/2016', '246': '4/3/2016', '247': '4/4/2016', '248': '4/5/2016', '249': '3/29/2016', '250': '3/30/2016', '251': '3/31/2016', '252': '4/1/2016', '253': '4/2/2016', '254': '4/3/2016', '255': '4/4/2016', '256': '4/5/2016', '257': '4/6/2016', '258': '4/7/2016', '259': '4/8/2016', '260': '4/9/2016', '261': '4/10/2016', '262': '4/11/2016', '263': '4/12/2016', '264': '4/1/2016', '265': '4/2/2016', '266': '4/3/2016', '267': '4/4/2016', '268': '4/5/2016', '269': '4/6/2016', '270': '4/7/2016', '271': '4/8/2016', '272': '4/9/2016', '273': '4/10/2016', '274': '4/11/2016', '275': '4/12/2016', '276': '3/29/2016', '277': '3/30/2016', '278': '3/31/2016', '279': '4/1/2016', '280': '4/2/2016', '281': '4/3/2016', '282': '4/4/2016', '283': '4/5/2016', '284': '4/6/2016', '285': '4/7/2016', '286': '4/8/2016', '287': '4/9/2016', '288': '4/10/2016', '289': '4/11/2016', '290': '4/12/2016', '291': '4/1/2016', '292': '4/2/2016', '293': '4/3/2016', '294': '4/4/2016', '295': '4/5/2016', '296': '4/6/2016', '297': '4/7/2016', '298': '4/8/2016', '299': '4/9/2016', '300': '4/10/2016', '301': '4/11/2016', '302': '4/12/2016', '303': '4/1/2016', '304': '4/2/2016', '305': '4/3/2016', '306': '4/4/2016', '307': '4/5/2016', '308': '4/6/2016', '309': '4/7/2016', '310': '4/8/2016', '311': '4/9/2016', '312': '4/10/2016', '313': '4/11/2016', '314': '4/1/2016', '315': '4/2/2016', '316': '4/3/2016', '317': '4/4/2016', '318': '4/5/2016', '319': '4/6/2016', '320': '4/7/2016', '321': '4/8/2016', '322': '4/9/2016', '323': '4/10/2016', '324': '4/1/2016', '325': '4/2/2016', '326': '4/3/2016', '327': '4/4/2016', '328': '4/5/2016', '329': '4/6/2016', '330': '4/7/2016', '331': '4/8/2016', '332': '4/9/2016', '333': '4/10/2016', '334': '4/1/2016', '335': '4/2/2016', '336': '4/3/2016', '337': '4/4/2016', '338': '4/5/2016', '339': '4/6/2016', '340': '4/7/2016', '341': '4/8/2016', '342': '4/9/2016', '343': '4/1/2016', '344': '4/2/2016', '345': '4/3/2016', '346': '4/4/2016', '347': '4/5/2016', '348': '4/6/2016', '349': '4/7/2016', '350': '4/8/2016', '351': '4/9/2016', '352': '3/30/2016', '353': '3/31/2016', '354': '4/1/2016', '355': '4/2/2016', '356': '4/3/2016', '357': '4/4/2016', '358': '4/5/2016', '359': '4/6/2016', '360': '4/7/2016', '361': '4/8/2016', '362': '4/9/2016', '363': '4/10/2016', '364': '4/11/2016', '365': '4/12/2016', '366': '4/1/2016', '367': '4/2/2016', '368': '4/3/2016', '369': '4/4/2016', '370': '4/5/2016', '371': '4/6/2016', '372': '4/7/2016', '373': '4/8/2016', '374': '4/9/2016', '375': '4/10/2016', '376': '4/11/2016', '377': '4/12/2016', '378': '4/1/2016', '379': '4/2/2016', '380': '4/3/2016', '381': '4/4/2016', '382': '4/5/2016', '383': '4/6/2016', '384': '4/7/2016', '385': '4/8/2016', '386': '4/9/2016', '387': '4/10/2016', '388': '4/11/2016', '389': '4/12/2016', '390': '4/2/2016', '391': '4/3/2016', '392': '4/4/2016', '393': '4/5/2016', '394': '4/6/2016', '395': '4/7/2016', '396': '4/8/2016', '397': '4/9/2016', '398': '4/10/2016', '399': '4/11/2016', '400': '4/12/2016', '401': '4/1/2016', '402': '4/2/2016', '403': '4/3/2016', '404': '4/4/2016', '405': '4/5/2016', '406': '4/6/2016', '407': '4/7/2016', '408': '4/8/2016', '409': '4/9/2016', '410': '4/10/2016', '411': '4/11/2016', '412': '4/12/2016', '413': '4/1/2016', '414': '4/2/2016', '415': '4/3/2016', '416': '4/4/2016', '417': '4/5/2016', '418': '4/6/2016', '419': '4/7/2016', '420': '4/8/2016', '421': '4/9/2016', '422': '4/10/2016', '423': '4/11/2016', '424': '4/12/2016', '425': '4/1/2016', '426': '4/2/2016', '427': '4/3/2016', '428': '4/4/2016', '429': '4/5/2016', '430': '4/6/2016', '431': '4/7/2016', '432': '4/8/2016', '433': '4/1/2016', '434': '4/2/2016', '435': '4/3/2016', '436': '4/4/2016', '437': '4/5/2016', '438': '4/6/2016', '439': '4/7/2016', '440': '4/8/2016', '441': '4/9/2016', '442': '4/10/2016', '443': '4/11/2016', '444': '4/12/2016', '445': '4/1/2016', '446': '4/2/2016', '447': '4/3/2016', '448': '4/4/2016', '449': '4/5/2016', '450': '4/6/2016', '451': '4/7/2016', '452': '4/8/2016', '453': '4/9/2016', '454': '4/10/2016', '455': '4/11/2016', '456': '4/12/2016'}, 'TotalSteps': {'0': 11004, '1': 17609, '2': 12736, '3': 13231, '4': 12041, '5': 10970, '6': 12256, '7': 12262, '8': 11248, '9': 10016, '10': 14557, '11': 14844, '12': 11974, '13': 10198, '14': 12521, '15': 12432, '16': 10057, '17': 10990, '18': 224, '19': 1810, '20': 815, '21': 1985, '22': 1905, '23': 1552, '24': 1675, '25': 4506, '26': 9218, '27': 1556, '28': 2910, '29': 18464, '30': 1335, '31': 1004, '32': 1111, '33': 6344, '34': 3572, '35': 3910, '36': 10000, '37': 6627, '38': 4636, '39': 20237, '40': 12912, '41': 2819, '42': 9921, '43': 8046, '44': 11166, '45': 7842, '46': 13840, '47': 1329, '48': 6847, '49': 5367, '50': 2841, '51': 0, '52': 0, '53': 7, '54': 6344, '55': 5316, '56': 4979, '57': 6556, '58': 5430, '59': 0, '60': 4317, '61': 5662, '62': 3198, '63': 2352, '64': 2234, '65': 1259, '66': 768, '67': 519, '68': 2523, '69': 2105, '70': 1209, '71': 24, '72': 13603, '73': 5477, '74': 11144, '75': 15313, '76': 10805, '77': 15392, '78': 18247, '79': 13023, '80': 16267, '81': 10005, '82': 10106, '83': 6717, '84': 2605, '85': 1229, '86': 2308, '87': 6679, '88': 5645, '89': 3180, '90': 2767, '91': 3762, '92': 3098, '93': 5142, '94': 3279, '95': 1019, '96': 0, '97': 0, '98': 0, '99': 0, '100': 4931, '101': 6999, '102': 1846, '103': 3417, '104': 4863, '105': 2277, '106': 11230, '107': 2098, '108': 10272, '109': 10533, '110': 6760, '111': 8328, '112': 15459, '113': 7485, '114': 10254, '115': 10114, '116': 11107, '117': 10320, '118': 10209, '119': 16081, '120': 10078, '121': 10001, '122': 0, '123': 890, '124': 2214, '125': 7640, '126': 9713, '127': 8432, '128': 7350, '129': 9353, '130': 7157, '131': 14103, '132': 5290, '133': 7497, '134': 0, '135': 0, '136': 0, '137': 0, '138': 0, '139': 4126, '140': 0, '141': 0, '142': 2063, '143': 5785, '144': 7625, '145': 4706, '146': 5861, '147': 4460, '148': 6406, '149': 7392, '150': 5551, '151': 8827, '152': 4662, '153': 4499, '154': 7618, '155': 11508, '156': 11943, '157': 12303, '158': 15425, '159': 8422, '160': 10226, '161': 14583, '162': 3573, '163': 3108, '164': 759, '165': 5543, '166': 3226, '167': 3023, '168': 5906, '169': 12483, '170': 8940, '171': 368, '172': 5702, '173': 10330, '174': 8778, '175': 6662, '176': 6309, '177': 1951, '178': 5563, '179': 4370, '180': 7144, '181': 2106, '182': 4152, '183': 5400, '184': 7428, '185': 5351, '186': 4299, '187': 6107, '188': 6429, '189': 6880, '190': 7476, '191': 6581, '192': 10480, '193': 7734, '194': 5129, '195': 2993, '196': 8, '197': 0, '198': 0, '199': 8433, '200': 0, '201': 2139, '202': 0, '203': 949, '204': 0, '205': 44, '206': 2660, '207': 5561, '208': 7239, '209': 7, '210': 0, '211': 0, 

### 2. While creating a table in mysql dont use manual approach to create it  ,always use a automation to create a table in mysql.

In [7]:
# !pip install pymysql
# !pip install sqlalchemy

In [8]:
import mysql.connector as conn
import pymysql
from sqlalchemy import create_engine

from MySQL_login import *

In [9]:
myDB = conn.connect(host= host, user = user, passwd = mysql_password)
print(myDB)

cursor = myDB.cursor()

cursor.execute("create database task31072022")

<mysql.connector.connection_cext.CMySQLConnection object at 0x0000024457F433A0>

In [10]:
database = 'task31072022'
port = '3306'
mydb = create_engine(f"mysql+pymysql://{user}:{mysql_password}@{host}:{port}/{database}", echo = False)

fitbit.to_sql(name = 'fitbit', con = mydb, index = False)

457

### 3. Convert all the dates available in dataset to timestamp format in pandas and in sql you to convert it in date format.

#### Pandas

In [11]:
fitbit['ActivityDate'] = pd.to_datetime(fitbit['ActivityDate'])
fitbit.dtypes

Id                                   int64
ActivityDate                datetime64[ns]
TotalSteps                           int64
TotalDistance                      float64
TrackerDistance                    float64
LoggedActivitiesDistance           float64
VeryActiveDistance                 float64
ModeratelyActiveDistance           float64
LightActiveDistance                float64
SedentaryActiveDistance            float64
VeryActiveMinutes                    int64
FairlyActiveMinutes                  int64
LightlyActiveMinutes                 int64
SedentaryMinutes                     int64
Calories                             int64
dtype: object

#### MySQL

In [12]:
r1 = cursor.execute("alter table task31072022.fitbit add column ActivityDate_new  date after ActivityDate;")
myDB.commit()
r2 = cursor.execute("SET SQL_SAFE_UPDATES = 0;")
myDB.commit()
r3 = cursor.execute("update task31072022.fitbit set ActivityDate_new = str_to_date(ActivityDate,'%m/%d/%Y')")
myDB.commit()

### 4. Find out in this data that how many unique id's we have.

In [13]:
fitbit.Id.value_counts().count()

35

### 5. Which id is one of the active id that you have in whole dataset.

In [14]:
fitbit.head(2)

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,2016-03-25,11004,7.11,7.11,0.0,2.57,0.46,4.07,0.0,33,12,205,804,1819
1,1503960366,2016-03-26,17609,11.55,11.55,0.0,6.92,0.73,3.91,0.0,89,17,274,588,2154

In [15]:
fitbit['Total_Active_Minutes'] = fitbit['VeryActiveMinutes']+fitbit['FairlyActiveMinutes']+fitbit['LightlyActiveMinutes']
fitbit.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,Total_Active_Minutes
0,1503960366,2016-03-25,11004,7.11,7.11,0.0,2.57,0.46,4.07,0.0,33,12,205,804,1819,250
1,1503960366,2016-03-26,17609,11.55,11.55,0.0,6.92,0.73,3.91,0.0,89,17,274,588,2154,380
2,1503960366,2016-03-27,12736,8.53,8.53,0.0,4.66,0.16,3.71,0.0,56,5,268,605,1944,329
3,1503960366,2016-03-28,13231,8.93,8.93,0.0,3.19,0.79,4.95,0.0,39,20,224,1080,1932,283
4,1503960366,2016-03-29,12041,7.85,7.85,0.0,2.16,1.09,4.61,0.0,28,28,243,763,1886,299

In [16]:
most_active_by_minutes =  fitbit[fitbit['Total_Active_Minutes'] == max(fitbit['Total_Active_Minutes'])]
most_active_by_minutes

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,Total_Active_Minutes
139,2891001357,2016-04-02,4126,3.22,0.0,3.218688,0.0,0.0,3.22,0.0,0,0,720,720,2881,720

In [17]:
most_active_by_minutes_2 = fitbit.groupby('Id')['Total_Active_Minutes'].sum().sort_values(ascending=False)[0:1]
most_active_by_minutes_2

Id
1503960366    5318
Name: Total_Active_Minutes, dtype: int64

### 6. How many of them have not logged there activity find out in terms of number of ids.

In [18]:
fitbit.groupby('Id')['LoggedActivitiesDistance'].sum().apply(lambda x:x<1).value_counts()

True     30
False     5
Name: LoggedActivitiesDistance, dtype: int64

### 7. Find out who is the laziest person id that we have in dataset.

In [19]:
# most_lazy_by_minutes =  fitbit[(fitbit['SedentaryMinutes'] == max(fitbit['SedentaryMinutes']))]
# most_lazy_by_minutes

most_lazy_by_minutes = fitbit.groupby('Id')['Total_Active_Minutes'].sum().sort_values(ascending=True)[0:1]
most_lazy_by_minutes

Id
4388161847    0
Name: Total_Active_Minutes, dtype: int64

### 8. Explore over an internet that how much calories burn is required for a healthy person and find out how many healthy person we have in our dataset.

In [20]:
fitbit['ActivityDate'].value_counts()

2016-04-02    35
2016-04-03    35
2016-04-04    35
2016-04-05    35
2016-04-01    34
2016-04-06    33
2016-04-07    33
2016-04-08    33
2016-04-09    32
2016-04-10    29
2016-04-11    25
2016-04-12    24
2016-03-30    11
2016-03-31    11
2016-03-29    10
2016-03-26     4
2016-03-25     4
2016-03-28     4
2016-03-27     4
2016-03-12     2
2016-03-13     2
2016-03-14     2
2016-03-15     2
2016-03-16     2
2016-03-17     2
2016-03-18     2
2016-03-19     2
2016-03-20     2
2016-03-21     2
2016-03-22     2
2016-03-23     2
2016-03-24     2
Name: ActivityDate, dtype: int64

In [21]:
# healty person burns more than 2600 calories per day
# Data is of 32 days so they need to burn 2600*32 calories

fitbit.groupby('Id')['Calories'].sum().apply(lambda a : a > 2600*32).value_counts()

# only 1 person is healthy

False    34
True      1
Name: Calories, dtype: int64

### 9. How many person are not a regular person with respect to activity try to find out those.

In [22]:
fitbit[fitbit['Calories']<1]['Id'].count()

5

### 10. Who is the third most active person in this dataset find out those in pandas and in sql both.

#### Pandas

In [23]:
fitbit.groupby('Id')['Total_Active_Minutes'].sum().sort_values(ascending=False)[2:3]

Id
6962181067    4521
Name: Total_Active_Minutes, dtype: int64

#### MySQL

In [24]:
r4 = cursor.execute("alter table task31072022.fitbit add column TotalActiveMinute int;")
myDB.commit()
r5 = cursor.execute("update task31072022.fitbit set TotalActiveMinute = VeryActiveMinutes+FairlyActiveMinutes+LightlyActiveMinutes")
myDB.commit()

In [25]:
r6 = cursor.execute("select id, sum(TotalActiveMinute) from task31072022.fitbit group by Id ORDER BY sum(TotalActiveMinute) DESC LIMIT 1 OFFSET 2;")

In [26]:
for i in cursor.fetchall():
    print(i)

(6962181067, Decimal('4521'))

### 11. Who is the 5th most laziest person avilable in dataset, find it out.

In [27]:
fitbit.groupby('Id')['Total_Active_Minutes'].sum().sort_values(ascending=True)[4:5]

Id
8583815059    1117
Name: Total_Active_Minutes, dtype: int64

### 12. What is the total cummulative calories burn for a person, find out.

In [28]:
fitbit.groupby('Id')['Calories'].sum()

Id
1503960366    34128
1624580081    25705
1644430081    29164
1844505072    19391
1927972279    27048
2022484408    29704
2026352035    16266
2320127002    18385
2347167796    30320
2873212765    20349
2891001357    18187
3372868164    18603
3977333714    16777
4020332650    98412
4057192912    60913
4319703577    23931
4388161847    14442
4445114986    31617
4558609924    21962
4702921684    42322
5553957443    21630
5577150313    36303
6117666160    20993
6290855005    21656
6391747486    15868
6775888955    24523
6962181067    29249
7007744171    31525
7086361926    26124
8053475328    31825
8253242879    17556
8378563200    40274
8583815059    19130
8792009665    24884
8877689391    41414
Name: Calories, dtype: int64

</br></br></br></br>

### Task 2 - Superstore_USA

1. Load this data in sql and in pandas with a relation in sql. 
2. While loading this data you dont have to create a table manually you can use any automated approach to create a table and load a data in bulk in table.
3. Find out how many return that we have recived, with a product id.
4. Try to join order and return data both in sql and pandas. 
5. Try to find out how many unique customer that we have.
6. Try to find out in how many regions we are selling a product and who is a manager for a respective region.
7. Find out how many different differnet shipement mode that we have and what is a percentage usablity of all the shipment mode with respect to dataset.
8. Create a new coulmn and try to find our a diffrence between order date and shipment date.
9. Based on question number 8 find out for which order id we have shipment duration more than 10 days.
10. Try to find out a list of a returned order which sihpment duration was more then 15 days and find out that region manager as well.
11. Gorup by region and find out which region is more profitable.
12. Try to find out overall in which country we are giving more discount. 
13. Give me a list of unique postal code.
14. Which customer segement is more profitalble find it out.
15. Try to find out the 10th most loss making product category. 
16. Try to find out 10 top product with highest margins.

### 1. Load this data in sql and in pandas with a relation in sql.
### 2. While loading this data you dont have to create a table manually you can use any automated approach to create a table and load a data in bulk in table.

#### Pandas

In [1]:
import pandas as pd

In [2]:
orders = pd.read_excel("G:\Study\ineuron\Live coding in lectures\Pandas\data fsds -20220726T060614Z-001\data fsds\Superstore_USA.xlsx", "Orders", index_col= 'Row ID')
orders.head()

,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
Row ID,,,,,,,,,,,,,,,,,,,,,
18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.3200,2,5.90,88525
20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.5600,4,13.01,88522
23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.6400,7,49.92,88523
23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.5100,7,41.64,88523
23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.2023,8,1446.67,88523

In [3]:
returns = pd.read_excel("G:\Study\ineuron\Live coding in lectures\Pandas\data fsds -20220726T060614Z-001\data fsds\Superstore_USA.xlsx", "Returns")
returns.head()

   Order ID    Status
0        65  Returned
1       612  Returned
2       614  Returned
3       678  Returned
4       710  Returned

In [4]:
users = pd.read_excel("G:\Study\ineuron\Live coding in lectures\Pandas\data fsds -20220726T060614Z-001\data fsds\Superstore_USA.xlsx", "Users")
users.head()

    Region  Manager
0  Central    Chris
1     East     Erin
2    South      Sam
3     West  William

#### MySQL

In [5]:
import mysql.connector as conn
import pymysql
from sqlalchemy import create_engine

from MySQL_login import *

In [6]:
myDB = conn.connect(host= host, user = user, passwd = mysql_password)
print(myDB)

cursor = myDB.cursor()

<mysql.connector.connection_cext.CMySQLConnection object at 0x0000023744437E80>

In [7]:
database = 'task31072022'
port = '3306'
mydb = create_engine(f"mysql+pymysql://{user}:{mysql_password}@{host}:{port}/{database}", echo = False)

orders1 = pd.read_excel("G:\Study\ineuron\Live coding in lectures\Pandas\data fsds -20220726T060614Z-001\data fsds\Superstore_USA.xlsx", "Orders", names =["RowID","OrderPriority","Discount","UnitPrice","ShippingCost","CustomerID","CustomerName","ShipMode","CustomerSegment","ProductCategory","ProductSub-Category","ProductContainer","ProductName","ProductBase Margin","Region","StateorProvince","City","PostalCode","OrderDate","ShipDate","Profit","Quantityorderednew","Sales","OrderID"])
orders1.head()

orders1.to_sql(name = 'orders', con = mydb, index = False)

9426

In [8]:
returns1 = pd.read_excel("G:\Study\ineuron\Live coding in lectures\Pandas\data fsds -20220726T060614Z-001\data fsds\Superstore_USA.xlsx", "Returns", names =["OrderID","Status"])
returns1.to_sql(name = 'returns', con = mydb, index = False)

1634

In [9]:
users.to_sql(name = 'users', con = mydb, index = False)

4

### 3. Find out how many return that we have recived, with a product id.

In [10]:
return_orders = pd.merge(orders, returns)
return_orders

,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,...,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,Status
0,Low,0.05,5.85,2.27,21,Tony Wilkins Winters,Regular Air,Small Business,Office Supplies,Pens & Art Supplies,...,New York,New York City,10012,2011-04-20,2011-04-24,-6.8200,9,54.79,9895,Returned
1,Medium,0.01,4.91,0.50,117,Linda Weiss,Regular Air,Home Office,Office Supplies,Labels,...,Washington,Seattle,98103,2010-04-04,2010-04-06,112.0600,47,228.46,13959,Returned
2,Medium,0.09,4.00,1.30,117,Linda Weiss,Express Air,Home Office,Office Supplies,Paper,...,Washington,Seattle,98103,2010-04-04,2010-04-06,16.7900,19,77.61,13959,Returned
3,High,0.02,3.28,5.00,117,Linda Weiss,Regular Air,Home Office,Office Supplies,Pens & Art Supplies,...,Washington,Seattle,98103,2013-08-16,2013-08-18,-89.0600,52,190.52,36038,Returned
4,Low,0.02,11.97,5.81,272,Eleanor Swain,Regular Air,Small Business,Office Supplies,Pens & Art Supplies,...,North Carolina,Charlotte,28204,2013-08-12,2013-08-12,-81.9413,76,912.06,39490,Returned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,Not Specified,0.06,37.94,5.08,3075,Gordon Brandt,Regular Air,Corporate,Office Supplies,Paper,...,California,Los Angeles,90061,2013-01-04,2013-01-06,-33.9680,3,113.14,7107,Returned
94,Not Specified,0.10,55.29,5.08,3075,Gordon Brandt,Regular Air,Corporate,Office Supplies,Storage & Organization,...,California,Los Angeles,90061,2013-01-04,2013-01-05,163.1200,35,1886.52,7107,Returned
95,Medium,0.05,4.28,6.18,3075,Gordon Brandt,Express Air,Corporate,Office Supplies,Paper,...,California,Los Angeles,90061,2013-06-25,2013-06-27,-22.5600,12,73.71,42823,Returned
96,High,0.05,14.48,1.99,3079,Andrew Levine,Regular Air,Consumer,Technology,Computer Peripherals,...,Pennsylvania,Philadelphia,19112,2012-09-30,2012-10-02,165.2000,96,1337.67,13638,Returned
97,High,0.06,128.24,12.65,3251,Peter Brooks,Regular Air,Small Business,Furniture,Chairs & Chairmats,...,New York,New York City,10112,2012-09-11,2012-09-13,1844.9600,92,12002.16,47109,Returned

In [11]:
return_orders['Status'].value_counts()

Returned    98
Name: Status, dtype: int64

In [12]:
return_orders[(return_orders['Status'] == 'Returned')]['Order ID']

0      9895
1     13959
2     13959
3     36038
4     39490
      ...
93     7107
94     7107
95    42823
96    13638
97    47109
Name: Order ID, Length: 98, dtype: int64

### 4. Try to join order and return data both in sql and pandas.

#### Pandas

In [13]:
pd.merge(orders, returns)

,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,...,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,Status
0,Low,0.05,5.85,2.27,21,Tony Wilkins Winters,Regular Air,Small Business,Office Supplies,Pens & Art Supplies,...,New York,New York City,10012,2011-04-20,2011-04-24,-6.8200,9,54.79,9895,Returned
1,Medium,0.01,4.91,0.50,117,Linda Weiss,Regular Air,Home Office,Office Supplies,Labels,...,Washington,Seattle,98103,2010-04-04,2010-04-06,112.0600,47,228.46,13959,Returned
2,Medium,0.09,4.00,1.30,117,Linda Weiss,Express Air,Home Office,Office Supplies,Paper,...,Washington,Seattle,98103,2010-04-04,2010-04-06,16.7900,19,77.61,13959,Returned
3,High,0.02,3.28,5.00,117,Linda Weiss,Regular Air,Home Office,Office Supplies,Pens & Art Supplies,...,Washington,Seattle,98103,2013-08-16,2013-08-18,-89.0600,52,190.52,36038,Returned
4,Low,0.02,11.97,5.81,272,Eleanor Swain,Regular Air,Small Business,Office Supplies,Pens & Art Supplies,...,North Carolina,Charlotte,28204,2013-08-12,2013-08-12,-81.9413,76,912.06,39490,Returned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,Not Specified,0.06,37.94,5.08,3075,Gordon Brandt,Regular Air,Corporate,Office Supplies,Paper,...,California,Los Angeles,90061,2013-01-04,2013-01-06,-33.9680,3,113.14,7107,Returned
94,Not Specified,0.10,55.29,5.08,3075,Gordon Brandt,Regular Air,Corporate,Office Supplies,Storage & Organization,...,California,Los Angeles,90061,2013-01-04,2013-01-05,163.1200,35,1886.52,7107,Returned
95,Medium,0.05,4.28,6.18,3075,Gordon Brandt,Express Air,Corporate,Office Supplies,Paper,...,California,Los Angeles,90061,2013-06-25,2013-06-27,-22.5600,12,73.71,42823,Returned
96,High,0.05,14.48,1.99,3079,Andrew Levine,Regular Air,Consumer,Technology,Computer Peripherals,...,Pennsylvania,Philadelphia,19112,2012-09-30,2012-10-02,165.2000,96,1337.67,13638,Returned
97,High,0.06,128.24,12.65,3251,Peter Brooks,Regular Air,Small Business,Furniture,Chairs & Chairmats,...,New York,New York City,10112,2012-09-11,2012-09-13,1844.9600,92,12002.16,47109,Returned

#### MySQL

In [14]:
r3 = cursor.execute("select * from task31072022.returns inner join task31072022.orders on orders.OrderID = returns.OrderID;")

In [15]:
for i in cursor.fetchall():
    print(i)

(9895, 'Returned', 1359, 'Low', 0.05, 5.85, 2.27, 21, 'Tony Wilkins Winters', 'Regular Air', 'Small Business', 'Office Supplies', 'Pens & Art Supplies', 'Wrap Bag', 'Dixon My First Ticonderoga Pencil, #2', 0.56, 'East', 'New York', 'New York City', 10012, datetime.datetime(2011, 4, 20, 0, 0), datetime.datetime(2011, 4, 24, 0, 0), -6.82, 9, 54.79, 9895)
(13959, 'Returned', 1950, 'Medium', 0.01, 4.91, 0.5, 117, 'Linda Weiss', 'Regular Air', 'Home Office', 'Office Supplies', 'Labels', 'Small Box', 'Avery 493', 0.36, 'West', 'Washington', 'Seattle', 98103, datetime.datetime(2010, 4, 4, 0, 0), datetime.datetime(2010, 4, 6, 0, 0), 112.06, 47, 228.46, 13959)
(13959, 'Returned', 1951, 'Medium', 0.09, 4.0, 1.3, 117, 'Linda Weiss', 'Express Air', 'Home Office', 'Office Supplies', 'Paper', 'Wrap Bag', 'EcoTones® Memo Sheets', 0.37, 'West', 'Washington', 'Seattle', 98103, datetime.datetime(2010, 4, 4, 0, 0), datetime.datetime(2010, 4, 6, 0, 0), 16.79, 19, 77.61, 13959)
(36038, 'Returned', 5055, 'High', 0.02, 3.28, 5.0, 117, 'Linda Weiss', 'Regular Air', 'Home Office', 'Office Supplies', 'Pens & Art Supplies', 'Wrap Bag', 'Newell 35', 0.56, 'West', 'Washington', 'Seattle', 98103, datetime.datetime(2013, 8, 16, 0, 0), datetime.datetime(2013, 8, 18, 0, 0), -89.06, 52, 190.52, 36038)
(39490, 'Returned', 5573, 'Low', 0.02, 11.97, 5.81, 272, 'Eleanor Swain', 'Regular Air', 'Small Business', 'Office Supplies', 'Pens & Art Supplies', 'Small Pack', 'Staples SlimLine Pencil Sharpener', 0.6, 'South', 'North Carolina', 'Charlotte', 28204, datetime.datetime(2013, 8, 12, 0, 0), datetime.datetime(2013, 8, 12, 0, 0), -81.9413, 76, 912.06, 39490)
(39490, 'Returned', 5574, 'Low', 0.03, 159.31, 60.0, 272, 'Eleanor Swain', 'Delivery Truck', 'Small Business', 'Furniture', 'Tables', 'Jumbo Drum', 'Hon Non-Folding Utility Tables', 0.55, 'South', 'North Carolina', 'Charlotte', 28204, datetime.datetime(2013, 8, 12, 0, 0), datetime.datetime(2013, 8, 16, 0, 0), 11.034899999999999, 34, 5689.28, 39490)
(37760, 'Returned', 5302, 'High', 0.01, 8.33, 1.99, 308, 'Glen Caldwell', 'Regular Air', 'Small Business', 'Technology', 'Computer Peripherals', 'Small Pack', '80 Minute Slim Jewel Case CD-R , 10/Pack - Staples', 0.52, 'West', 'Washington', 'Seattle', 98115, datetime.datetime(2010, 8, 14, 0, 0), datetime.datetime(2010, 8, 15, 0, 0), 10.74, 32, 280.62, 37760)
(37760, 'Returned', 5303, 'High', 0.04, 85.99, 0.99, 308, 'Glen Caldwell', 'Regular Air', 'Small Business', 'Technology', 'Telephones and Communication', 'Wrap Bag', 'Accessory34', 0.55, 'West', 'Washington', 'Seattle', 98115, datetime.datetime(2013, 8, 14, 0, 0), datetime.datetime(2013, 8, 16, 0, 0), 897.867, 76, 5546.06, 37760)
(37414, 'Returned', 5257, 'Low', 0.09, 550.98, 64.59, 349, 'Kim Weiss', 'Delivery Truck', 'Home Office', 'Furniture', 'Tables', 'Jumbo Box', 'Chromcraft Bull-Nose Wood 48" x 96" Rectangular Conference Tables', 0.66, 'South', 'Florida', 'Miami', 33132, datetime.datetime(2012, 9, 9, 0, 0), datetime.datetime(2012, 9, 11, 0, 0), -1770.9659767800001, 76, 40136.93, 37414)
(47265, 'Returned', 6643, 'Critical', 0.02, 5.98, 5.46, 349, 'Kim Weiss', 'Regular Air', 'Home Office', 'Office Supplies', 'Paper', 'Small Box', 'Xerox 1983', 0.36, 'South', 'Florida', 'Miami', 33132, datetime.datetime(2012, 12, 10, 0, 0), datetime.datetime(2012, 12, 11, 0, 0), -80.9039, 62, 374.26, 47265)
(7079, 'Returned', 979, 'Medium', 0.01, 280.98, 57.0, 478, 'Michael Wiggins', 'Delivery Truck', 'Small Business', 'Furniture', 'Chairs & Chairmats', 'Jumbo Drum', 'Hon 2090 “Pillow Soft” Series Mid Back Swivel/Tilt Chairs', 0.78, 'East', 'New York', 'New York City', 10177, datetime.datetime(2011, 2, 8, 0, 0), datetime.datetime(2011, 2, 9, 0, 0), -416.7, 44, 12296.49, 7079)
(7079, 'Returned', 980, 'Medium', 0.03, 6.48, 5.94, 478, 'Michael Wiggins', 'Regular Air', 'Small Business', 'Office Supplies', 'Paper', 'Small Box', 'Eureka Recycled Copy Paper 8 1/2" x 11", Ream', 0.37, 'East', 'New York', 'New York City', 10177, datetime.datetime(2011, 2, 8, 0, 0), datetime.datetime(2011, 2, 10, 0, 0), -34.91, 18, 128.13, 7079)
(8353, 'Returned', 1147, 'Medium', 0.08, 2.94, 0.96, 491, 'Toni Swanson', 'Regular Air', 'Consumer', 'Office Supplies', 'Pens & Art Supplies', 'Wrap Bag', 'Newell 343', 0.58, 'East', 'New York', 'New York City', 10154, datetime.datetime(2010, 5, 15, 0, 0), datetime.datetime(2010, 5, 17, 0, 0), -2.12, 23, 66.7, 8353)
(8353, 'Returned', 1146, 'Medium', 0.06, 8.32, 2.38, 491, 'Toni Swanson', 'Regular Air', 'Consumer', 'Technology', 'Computer Peripherals', 'Small Pack', 'Imation 3.5 IBM Formatted Diskettes, 10/Box', 0.74, 'East', 'New York', 'New York City', 10154, datetime.datetime(2013, 5, 15, 0, 0), datetime.datetime(2013, 5, 17, 0, 0), -36.63, 44, 371.28, 8353)
(17155, 'Returned', 2368, 'Medium', 0.0, 6.88, 2.0, 553, 'Kristine Connolly', 'Express Air', 'Home Office', 'Office Supplies', 'Paper', 'Wrap Bag', 'Adams Phone Message Book, 200 Message Capacity, 8 1/16” x 11”', 0.39, 'West', 'California', 'Los Angeles', 90008, datetime.datetime(2010, 1, 28, 0, 0), datetime.datetime(2010, 1, 29, 0, 0), 34.068000000000005, 36, 267.53, 17155)
(17155, 'Returned', 2369, 'Medium', 0.03, 32.48, 35.0, 553, 'Kristine Connolly', 'Express Air', 'Home Office', 'Office Supplies', 'Storage & Organization', 'Large Box', 'Fellowes Neat Ideas® Storage Cubes', 0.81, 'West', 'California', 'Los Angeles', 90008, datetime.datetime(2013, 1, 28, 0, 0), datetime.datetime(2013, 1, 28, 0, 0), -1440.4319999999998, 34, 1168.35, 17155)
(48487, 'Returned', 6813, 'Low', 0.0, 12.97, 1.49, 604, 'Lindsay P Ashley', 'Regular Air', 'Home Office', 'Office Supplies', 'Binders and Binder Accessories', 'Small Box', 'Mead 1st Gear 2" Zipper Binder, Asst. Colors', 0.35, 'West', 'California', 'Los Angeles', 90045, datetime.datetime(2011, 1, 11, 0, 0), datetime.datetime(2011, 1, 13, 0, 0), 58.46640000000001, 27, 360.7, 48487)
(55968, 'Returned', 7828, 'Low', 0.05, 1.82, 1.0, 604, 'Lindsay P Ashley', 'Regular Air', 'Home Office', 'Office Supplies', 'Pens & Art Supplies', 'Wrap Bag', 'Crayola Anti Dust Chalk, 12/Pack', 0.4, 'West', 'California', 'Los Angeles', 90045, datetime.datetime(2013, 9, 30, 0, 0), datetime.datetime(2013, 10, 2, 0, 0), 0.86, 84, 154.6, 55968)
(56452, 'Returned', 7893, 'Not Specified', 0.0, 236.97, 59.24, 640, 'Neal Wolfe', 'Delivery Truck', 'Consumer', 'Furniture', 'Tables', 'Jumbo Box', 'Chromcraft Rectangular Conference Tables', 0.61, 'West', 'Washington', 'Seattle', 98119, datetime.datetime(2010, 2, 14, 0, 0), datetime.datetime(2010, 2, 15, 0, 0), 1192.04, 34, 6686.34, 56452)
(26784, 'Returned', 3749, 'Critical', 0.02, 120.98, 30.0, 699, 'Jenny Gold', 'Delivery Truck', 'Consumer', 'Furniture', 'Chairs & Chairmats', 'Jumbo Drum', 'Hon Every-Day® Chair Series Swivel Task Chairs', 0.64, 'West', 'California', 'Los Angeles', 90041, datetime.datetime(2011, 7, 23, 0, 0), datetime.datetime(2011, 7, 24, 0, 0), -64.14, 14, 1711.44, 26784)
(57638, 'Returned', 8079, 'Low', 0.09, 217.85, 29.1, 699, 'Jenny Gold', 'Delivery Truck', 'Consumer', 'Furniture', 'Tables', 'Jumbo Box', 'Chromcraft Bull-Nose Wood Round Conference Table Top, Wood Base', 0.68, 'West', 'California', 'Los Angeles', 90041, datetime.datetime(2013, 4, 22, 0, 0), datetime.datetime(2013, 4, 27, 0, 0), -526.478095, 35, 5740.62, 57638)
(57638, 'Returned', 8080, 'Low', 0.07, 11.48, 5.43, 699, 'Jenny Gold', 'Regular Air', 'Consumer', 'Office Supplies', 'Paper', 'Small Box', 'Personal Creations™ Ink Jet Cards and Labels', 0.36, 'West', 'California', 'Los Angeles', 90041, datetime.datetime(2013, 4, 22, 0, 0), datetime.datetime(2013, 4, 24, 0, 0), 78.89, 49, 570.43, 57638)
(57638, 'Returned', 8081, 'Low', 0.08, 2.08, 2.56, 699, 'Jenny Gold', 'Regular Air', 'Consumer', 'Office Supplies', 'Scissors, Rulers and Trimmers', 'Small Pack', 'Kleencut® Forged Office Shears by Acme United Corporation', 0.55, 'West', 'California', 'Los Angeles', 90041, datetime.datetime(2013, 4, 22, 0, 0), datetime.datetime(2013, 4, 24, 0, 0), -85.58, 49, 100.08, 57638)
(26784, 'Returned', 3750, 'Critical', 0.09, 13.99, 7.51, 699, 'Jenny Gold', 'Regular Air', 'Consumer', 'Technology', 'Office Machines', 'Medium Box', 'Sharp EL500L Fraction Calculator', 0.39, 'West', 'California', 'Los Angeles', 90041, datetime.datetime(2013, 7, 23, 0, 0), datetime.datetime(2013, 7, 24, 0, 0), -37.9407, 46, 613.65, 26784)
(50246, 'Returned', 7038, 'Medium', 0.05, 6.48, 7.37, 894, 'Gail Rankin Cole', 'Express Air', 'Corporate', 'Office Supplies', 'Paper', 'Small Box', 'Xerox 210', 0.37, 'East', 'District of Columbia', 'Washington', 20024, datetime.datetime(2011, 8, 18, 0, 0), datetime.datetime(2011, 8, 19, 0, 0), -47.67, 25, 182.21, 50246)
(51559, 'Returned', 7234, 'Low', 0.09, 25.98, 4.08, 949, 'Ernest Oh', 'Regular Air', 'Consumer', 'Office Supplies', 'Pens & Art Supplies', 'Small Pack', 'Boston 1799 Powerhouse™ Electric Pencil Sharpener', 0.57, 'West', 'California', 'Los Angeles', 90049, datetime.datetime(2013, 3, 4, 0, 0), datetime.datetime(2013, 3, 13, 0, 0), 129.81, 34, 823.98, 51559)
(47813, 'Returned', 6711, 'High', 0.0, 6.68, 5.66, 1044, 'Erin Ballard', 'Regular Air', 'Home Office', 'Office Supplies', 'Paper', 'Small Box', 'Xerox 1923', 0.37, 'West', 'California', 'Los Angeles', 90004, datetime.datetime(2010, 8, 27, 0, 0), datetime.datetime(2010, 8, 29, 0, 0), -76.94, 90, 617.4, 47813)
(31303, 'Returned', 4398, 'Low', 0.09, 5.98, 1.49, 1044, 'Erin Ballard', 'Express Air', 'Home Office', 'Office Supplies', 'Binders and Binder Accessories', 'Small Box', 'Avery Hanging File Binders', 0.39, 'West', 'California', 'Los Angeles', 90004, datetime.datetime(2012, 3, 20, 0, 0), datetime.datetime(2012, 3, 22, 0, 0), 87.601, 56, 342.87, 31303)
(56931, 'Returned', 7966, 'High', 0.05, 7.99, 5.03, 1060, 'Gene Gilliam', 'Regular Air', 'Small Business', 'Technology', 'Telephones and Communication', 'Medium Box', 'Bell Sonecor JB700 Caller ID', 0.6, 'South', 'Georgia', 'Atlanta', 30318, datetime.datetime(2011, 2, 3, 0, 0), datetime.datetime(2011, 2, 5, 0, 0), -147.09002, 34, 232.42, 56931)
(17985, 'Returned', 2474, 'Medium', 0.01, 110.98, 30.0, 1104, 'Timothy Ross', 'Delivery Truck', 'Home Office', 'Furniture', 'Chairs & Chairmats', 'Jumbo Drum', 'Office Star Flex Back Scooter Chair with White Frame', 0.71, 'East', 'New York', 'New York City', 10282, datetime.datetime(2012, 4, 12, 0, 0), datetime.datetime(2012, 4, 13, 0, 0), -183.26, 4, 473.88, 17985)
(17985, 'Returned', 2475, 'Medium', 0.07, 20.99, 3.3, 1104, 'Timothy Ross', 'Regular Air', 'Home Office', 'Technology', 'Telephones and Communication', 'Small Pack', 'Accessory39', 0.81, 'East', 'New York', 'New York City', 10282, datetime.datetime(2012, 4, 12, 0, 0), datetime.datetime(2012, 4, 14, 0, 0), -133.309, 56, 950.91, 17985)
(24519, 'Returned', 3435, 'Critical', 0.03, 5.34, 5.63, 1106, 'Maxine Collier Grady', 'Regular Air', 'Consumer', 'Office Supplies', 'Binders and Binder Accessories', 'Small Box', 'Pressboard Data Binder, Crimson, 12" X 8 1/2"', 0.39, 'Central', 'Texas', 'Dallas', 75220, datetime.datetime(2012, 6, 11, 0, 0), datetime.datetime(2012, 6, 12, 0, 0), -60.72, 36, 208.73, 24519)
(54914, 'Returned', 7659, 'Critical', 0.06, 5.98, 5.46, 1106, 'Maxine Collier Grady', 'Regular Air', 'Small Business', 'Office Supplies', 'Paper', 'Small Box', 'Xerox 1983', 0.36, 'Central', 'Texas', 'Dallas', 75220, datetime.datetime(2012, 8, 28, 0, 0), datetime.datetime(2012, 8, 29, 0, 0), -57.64, 63, 389.67, 54914)
(54914, 'Returned', 7660, 'Critical', 0.06, 12.44, 6.27, 1106, 'Maxine Collier Grady', 'Regular Air', 'Small Business', 'Office Supplies', 'Storage & Organization', 'Medium Box', 'Eldon Simplefile® Box Office®', 0.57, 'Central', 'Texas', 'Dallas', 75220, datetime.datetime(2012, 8, 28, 0, 0), datetime.datetime(2012, 8, 30, 0, 0), -27.83, 14, 181.16, 54914)
(33477, 'Returned', 4697, 'High', 0.08, 10.35, 0.99, 1106, 'Maxine Collier Grady', 'Regular Air', 'Small Business', 'Office Supplies', 'Labels', 'Small Box', 'Avery 503', 0.37, 'Central', 'Texas', 'Dallas', 75220, datetime.datetime(2013, 10, 19, 0, 0), datetime.datetime(2013, 10, 21, 0, 0), 113.63, 59, 567.41, 33477)
(54595, 'Returned', 7632, 'Medium', 0.09, 130.98, 30.0, 1217, 'Billy Perry Browning', 'Delivery Truck', 'Small Business', 'Furniture', 'Chairs & Chairmats', 'Jumbo Drum', 'Office Star - Contemporary Task Swivel chair with 2-way adjustable arms, Plum', 0.78, 'East', 'Massachusetts', 'Boston', 2112, datetime.datetime(2010, 4, 28, 0, 0), datetime.datetime(2010, 5, 1, 0, 0), -421.76, 41, 5258.94, 54595)
(15009, 'Returned', 2099, 'Not Specified', 0.09, 28.15, 8.99, 1217, 'Billy Perry Browning', 'Express Air', 'Small Business', 'Office Supplies', 'Pens & Art Supplies', 'Small Pack', 'Boston Electric Pencil Sharpener, Model 1818, Charcoal Black', 0.57, 'East', 'Massachusetts', 'Boston', 2112, datetime.datetime(2012, 12, 21, 0, 0), datetime.datetime(2012, 12, 23, 0, 0), -7.8, 92, 2400.26, 15009)
(15009, 'Returned', 2100, 'Not Specified', 0.08, 7.78, 2.5, 1217, 'Billy Perry Browning', 'Express Air', 'Small Business', 'Office Supplies', 'Envelopes', 'Small Box', 'Staples #10 Colored Envelopes', 0.38, 'East', 'Massachusetts', 'Boston', 2112, datetime.datetime(2012, 12, 21, 0, 0), datetime.datetime(2012, 12, 22, 0, 0), 61.09, 56, 458.86, 15009)
(54595, 'Returned', 7631, 'Medium', 0.02, 8.34, 2.64, 1217, 'Billy Perry Browning', 'Regular Air', 'Small Business', 'Office Supplies', 'Scissors, Rulers and Trimmers', 'Small Pack', 'Acme® Elite Stainless Steel Scissors', 0.59, 'East', 'Massachusetts', 'Boston', 2112, datetime.datetime(2013, 4, 28, 0, 0), datetime.datetime(2013, 4, 30, 0, 0), 6.79, 30, 250.29, 54595)
(55874, 'Returned', 7810, 'Medium', 0.0, 7.1, 6.05, 1228, 'Hazel Jennings', 'Regular Air', 'Small Business', 'Office Supplies', 'Binders and Binder Accessories', 'Small Box', 'Wilson Jones Hanging View Binder, White, 1"', 0.39, 'East', 'Pennsylvania', 'Philadelphia', 19140, datetime.datetime(2010, 2, 16, 0, 0), datetime.datetime(2010, 2, 17, 0, 0), -60.145, 28, 208.83, 55874)
(55874, 'Returned', 7811, 'Medium', 0.01, 4.98, 4.62, 1228, 'Hazel Jennings', 'Express Air', 'Small Business', 'Technology', 'Computer Peripherals', 'Small Pack', 'Imation 3.5", DISKETTE 44766 HGHLD3.52HD/FM, 10/Pack', 0.64, 'East', 'Pennsylvania', 'Philadelphia', 19140, datetime.datetime(2010, 2, 16, 0, 0), datetime.datetime(2010, 2, 18, 0, 0), -111.72, 41, 228.3, 55874)
(55874, 'Returned', 7812, 'Medium', 0.06, 5.68, 1.39, 1228, 'Hazel Jennings', 'Regular Air', 'Small Business', 'Office Supplies', 'Envelopes', 'Small Box', 'Staples Standard Envelopes', 0.38, 'East', 'Pennsylvania', 'Philadelphia', 19140, datetime.datetime(2010, 2, 16, 0, 0), datetime.datetime(2010, 2, 16, 0, 0), 33.01, 24, 129.53, 55874)
(41760, 'Returned', 5882, 'Low', 0.04, 315.98, 19.99, 1228, 'Hazel Jennings', 'Regular Air', 'Small Business', 'Office Supplies', 'Binders and Binder Accessories', 'Small Box', 'GBC ProClick™ 150 Presentation Binding System', 0.38, 'East', 'Pennsylvania', 'Philadelphia', 19140, datetime.datetime(2013, 1, 27, 0, 0), datetime.datetime(2013, 2, 1, 0, 0), 1059.2326, 23, 7325.68, 41760)
(41760, 'Returned', 5883, 'Low', 0.0, 9.98, 12.52, 1228, 'Hazel Jennings', 'Regular Air', 'Small Business', 'Furniture', 'Office Furnishings', 'Small Box', 'Eldon® Expressions™ Wood and Plastic Desk Accessories, Oak', 0.57, 'East', 'Pennsylvania', 'Philadelphia', 19140, datetime.datetime(2013, 1, 27, 0, 0), datetime.datetime(2013, 2, 3, 0, 0), -213.08800000000002, 24, 269.95, 41760)
(41760, 'Returned', 5884, 'Low', 0.08, 115.99, 2.5, 1228, 'Hazel Jennings', 'Regular Air', 'Small Business', 'Technology', 'Telephones and Communication', 'Small Box', '6160', 0.57, 'East', 'Pennsylvania', 'Philadelphia', 19140, datetime.datetime(2013, 1, 27, 0, 0), datetime.datetime(2013, 2, 1, 0, 0), -446.1952, 8, 783.68, 41760)
(41760, 'Returned', 5885, 'Low', 0.05, 95.99, 8.99, 1228, 'Hazel Jennings', 'Regular Air', 'Small Business', 'Technology', 'Telephones and Communication', 'Small Box', '600 Series Flip', 0.57, 'East', 'Pennsylvania', 'Philadelphia', 19140, datetime.datetime(2013, 1, 27, 0, 0), datetime.datetime(2013, 2, 1, 0, 0), 278.78040000000004, 44, 3555.35, 41760)
(53285, 'Returned', 7466, 'Critical', 0.04, 165.98, 19.99, 1246, 'Lois Hansen', 'Regular Air', 'Home Office', 'Office Supplies', 'Binders and Binder Accessories', 'Small Box', 'GBC DocuBind P100 Manual Binding Machine', 0.4, 'East', 'New York', 'New York City', 10009, datetime.datetime(2013, 5, 24, 0, 0), datetime.datetime(2013, 5, 26, 0, 0), 163.8035, 8, 1390.61, 53285)
(22656, 'Returned', 3155, 'Not Specified', 0.05, 30.98, 6.5, 1280, 'Harold Albright', 'Express Air', 'Corporate', 'Technology', 'Computer Peripherals', 'Small Box', 'Belkin ErgoBoard™ Keyboard', 0.64, 'West', 'Washington', 'Seattle', 98119, datetime.datetime(2011, 12, 22, 0, 0), datetime.datetime(2011, 12, 24, 0, 0), -77.89, 19, 587.67, 22656)
(49762, 'Returned', 6959, 'High', 0.09, 2.94, 0.81, 1313, 'Katherine Knight', 'Regular Air', 'Corporate', 'Office Supplies', 'Pens & Art Supplies', 'Wrap Bag', 'Prang Colored Pencils', 0.4, 'East', 'Pennsylvania', 'Philadelphia', 19134, datetime.datetime(2012, 6, 15, 0, 0), datetime.datetime(2012, 6, 17, 0, 0), 23.74, 58, 164.27, 49762)
(15303, 'Returned', 2143, 'Critical', 0.02, 4.54, 5.83, 1314, 'Keith Marsh', 'Regular Air', 'Home Office', 'Office Supplies', 'Binders and Binder Accessories', 'Small Box', 'Avery® Durable Plastic 1" Binders', 0.36, 'West', 'California', 'Los Angeles', 90058, datetime.datetime(2011, 9, 13, 0, 0), datetime.datetime(2011, 9, 14, 0, 0), -74.405, 38, 183.0, 15303)
(15303, 'Returned', 2144, 'Critical', 0.02, 28.48, 8.99, 1314, 'Keith Marsh', 'Regular Air', 'Home Office', 'Technology', 'Computer Peripherals', 'Small Pack', 'Imation IBM Formatted Diskettes, 100/Pack', 0.7, 'West', 'California', 'Los Angeles', 90058, datetime.datetime(2011, 9, 13, 0, 0), datetime.datetime(2011, 9, 15, 0, 0), -108.14, 33, 965.16, 15303)
(37380, 'Returned', 5252, 'Critical', 0.08, 26.64, 5.3, 1314, 'Keith Marsh', 'Regular Air', 'Home Office', 'Furniture', 'Chairs & Chairmats', 'Medium Box', 'SAFCO Optional Arm Kit for Workspace® Cribbage Stacking Chair', None, 'West', 'California', 'Los Angeles', 90058, datetime.datetime(2012, 4, 1, 0, 0), datetime.datetime(2012, 4, 2, 0, 0), 90.04, 32, 813.66, 37380)
(37380, 'Returned', 5253, 'Critical', 0.0, 9.99, 4.78, 1314, 'Keith Marsh', 'Regular Air', 'Home Office', 'Office Supplies', 'Paper', 'Small Box', 'Xerox 1896', 0.4, 'West', 'California', 'Los Angeles', 90058, datetime.datetime(2012, 4, 1, 0, 0), datetime.datetime(2012, 4, 2, 0, 0), 74.73, 53, 571.93, 37380)
(37380, 'Returned', 5254, 'Critical', 0.07, 3.55, 1.43, 1314, 'Keith Marsh', 'Regular Air', 'Home Office', 'Office Supplies', 'Rubber Bands', 'Wrap Bag', 'Acco Clips to Go™ Binder Clips, 24 Clips in Two Sizes', 0.38, 'West', 'California', 'Los Angeles', 90058, datetime.datetime(2012, 4, 1, 0, 0), datetime.datetime(2012, 4, 2, 0, 0), 27.37, 47, 169.19, 37380)
(49027, 'Returned', 6878, 'High', 0.08, 17.67, 8.99, 1314, 'Keith Marsh', 'Regular Air', 'Home Office', 'Furniture', 'Office Furnishings', 'Small Pack', 'Executive Impressions 12" Wall Clock', 0.47, 'West', 'California', 'Los Angeles', 90058, datetime.datetime(2012, 4, 11, 0, 0), datetime.datetime(2012, 4, 12, 0, 0), 35.08, 46, 795.27, 49027)
(54563, 'Returned', 7626, 'Critical', 0.01, 20.24, 8.99, 1318, 'Vickie Becker', 'Regular Air', 'Home Office', 'Furniture', 'Office Furnishings', 'Small Pack', 'DAX Metal Frame, Desktop, Stepped-Edge', 0.46, 'East', 'New York', 'New York City', 10280, datetime.datetime(2011, 10, 4, 0, 0), datetime.datetime(2011, 10, 6, 0, 0), 35.096, 43, 938.05, 54563)

### 5. Try to find out how many unique customer that we have.

In [16]:
len(orders['Customer ID'].unique())

2703

In [17]:
r4 = cursor.execute("select count(distinct CustomerID) from task31072022.orders") #2703
for i in cursor.fetchall():
    print(i)

(2703,)

In [18]:
cursor.close()

True

### 6. Try to find out in how many regions we are selling a product and who is a manager for a respective region.

In [19]:
region_orders = pd.merge(orders, users)
region_orders

,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,...,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,Manager
0,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,...,Illinois,Addison,60101,2012-05-28,2012-05-30,1.32000,2,5.90,88525,Chris
1,Medium,0.09,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,Office Furnishings,...,Minnesota,Prior Lake,55372,2010-05-12,2010-05-14,803.47050,16,1164.45,86838,Chris
2,Medium,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Pens & Art Supplies,...,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-24.03000,7,22.23,86838,Chris
3,Medium,0.05,3.28,4.20,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Pens & Art Supplies,...,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-37.03000,4,13.99,86838,Chris
4,Medium,0.05,3.58,1.63,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Rubber Bands,...,Minnesota,Prior Lake,55372,2010-05-12,2010-05-13,-0.71000,4,14.26,86838,Chris
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,Critical,0.10,4.98,4.70,3381,Christopher Norton Patterson,Regular Air,Home Office,Office Supplies,Paper,...,Georgia,Macon,31204,2013-10-09,2013-10-11,174.38400,15,69.66,88850,Sam
9422,Not Specified,0.00,58.14,36.61,3382,Jon Beasley,Delivery Truck,Corporate,Furniture,Bookcases,...,Georgia,Marietta,30062,2011-05-21,2011-05-21,12.42600,13,807.21,88842,Sam
9423,Not Specified,0.00,29.99,5.50,3382,Jon Beasley,Regular Air,Corporate,Technology,Computer Peripherals,...,Georgia,Marietta,30062,2011-05-21,2011-05-22,-94.55600,7,218.15,88842,Sam
9424,Not Specified,0.03,16.16,7.74,3382,Jon Beasley,Regular Air,Corporate,Furniture,Office Furnishings,...,Georgia,Marietta,30062,2011-05-21,2011-05-23,-5257.04634,1,20.17,88842,Sam
9425,Not Specified,0.04,5.98,7.15,3382,Jon Beasley,Regular Air,Corporate,Office Supplies,Paper,...,Georgia,Marietta,30062,2013-10-07,2013-10-09,-85.90400,3,21.86,88849,Sam

In [20]:
region_orders.columns

Index(['Order Priority', 'Discount', 'Unit Price', 'Shipping Cost',
       'Customer ID', 'Customer Name', 'Ship Mode', 'Customer Segment',
       'Product Category', 'Product Sub-Category', 'Product Container',
       'Product Name', 'Product Base Margin', 'Region', 'State or Province',
       'City', 'Postal Code', 'Order Date', 'Ship Date', 'Profit',
       'Quantity ordered new', 'Sales', 'Order ID', 'Manager'],
      dtype='object')

In [21]:
pd.DataFrame(region_orders.groupby(['Product Name', 'Region'])['Manager'].sum())

                                                                          Manager
Product Name                                       Region
"While you Were Out" Message Book, One Form per... Central             ChrisChris
                                                   South                      Sam
                                                   West     WilliamWilliamWilliam
#10 Self-Seal White Envelopes                      Central        ChrisChrisChris
                                                   West            WilliamWilliam
...                                                                           ...
iDEN i95                                           East                  ErinErin
                                                   South                      Sam
iDENi80s                                           Central        ChrisChrisChris
                                                   East                      Erin
                                                   West                   William

[3976 rows x 1 columns]

### 7. Find out how many different differnet shipement mode that we have and what is a percentage usablity of all the shipment mode with respect to dataset.

In [22]:
mode_cnt = pd.DataFrame(region_orders['Ship Mode'].value_counts())
mode_cnt

                Ship Mode
Regular Air          7036
Delivery Truck       1283
Express Air          1107

In [23]:
percent_shipmode_usage = mode_cnt[['Ship Mode']]/(mode_cnt.sum())*100
percent_shipmode_usage

                Ship Mode
Regular Air     74.644600
Delivery Truck  13.611288
Express Air     11.744112

### 8. Create a new coulmn and try to find our a diffrence between order date and shipment date.

In [24]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9426 entries, 18606 to 24492
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Order Priority        9426 non-null   object
 1   Discount              9426 non-null   float64
 2   Unit Price            9426 non-null   float64
 3   Shipping Cost         9426 non-null   float64
 4   Customer ID           9426 non-null   int64
 5   Customer Name         9426 non-null   object
 6   Ship Mode             9426 non-null   object
 7   Customer Segment      9426 non-null   object
 8   Product Category      9426 non-null   object
 9   Product Sub-Category  9426 non-null   object
 10  Product Container     9426 non-null   object
 11  Product Name          9426 non-null   object
 12  Product Base Margin   9354 non-null   float64
 13  Region                9426 non-null   object
 14  State or Province     9426 non-null   object
 15  City                  9426 non-null   object
 16  Postal Code           9426 non-null   int64
 17  Order Date            9426 non-null   datetime64[ns]
 18  Ship Date             9426 non-null   datetime64[ns]
 19  Profit                9426 non-null   float64
 20  Quantity ordered new  9426 non-null   int64
 21  Sales                 9426 non-null   float64
 22  Order ID              9426 non-null   int64
dtypes: datetime64[ns](2), float64(6), int64(4), object(11)
memory usage: 1.7+ MB

In [25]:
orders['Order_Duration'] = start=orders['Ship Date'] - orders['Order Date']
orders[['Order ID', 'Order_Duration']]

        Order ID Order_Duration
Row ID
18606      88525         2 days
20847      88522         1 days
23086      88523         1 days
23087      88523         1 days
23088      88523         0 days
...          ...            ...
20275      87532         1 days
20276      87532         0 days
24491      87533         2 days
25914      87530         3 days
24492      87533         2 days

[9426 rows x 2 columns]

### 9. Based on question number 8 find out for which order id we have shipment duration more than 10 days.

In [26]:
orders['Order_Duration'].dtype

dtype('<m8[ns]')

In [27]:
pd.DataFrame(orders[orders['Order_Duration'].dt.components['days'] > 10]['Order ID'])

        Order ID
Row ID
18246      87215
23091      86318
23092      86318
20703      87957
20704      87957
20705      87957
2703       19556
2704       19556
2705       19556
18060      86177
21603      88223
19005      88352
24392      87572
21257      91294
26351      86434
26350      86436
26352      86436
20750      87300
2748       19841
2749       19841
2750       19841
20748      87300
20749      87300

### 10. Try to find out a list of a returned order which sihpment duration was more then 15 days and find out that region manager as well.

In [28]:
region_orders = pd.merge(orders, users)
region_orders

,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,...,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,Order_Duration,Manager
0,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,...,Addison,60101,2012-05-28,2012-05-30,1.32000,2,5.90,88525,2 days,Chris
1,Medium,0.09,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,Office Furnishings,...,Prior Lake,55372,2010-05-12,2010-05-14,803.47050,16,1164.45,86838,2 days,Chris
2,Medium,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Pens & Art Supplies,...,Prior Lake,55372,2010-05-12,2010-05-13,-24.03000,7,22.23,86838,1 days,Chris
3,Medium,0.05,3.28,4.20,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Pens & Art Supplies,...,Prior Lake,55372,2010-05-12,2010-05-13,-37.03000,4,13.99,86838,1 days,Chris
4,Medium,0.05,3.58,1.63,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,Rubber Bands,...,Prior Lake,55372,2010-05-12,2010-05-13,-0.71000,4,14.26,86838,1 days,Chris
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,Critical,0.10,4.98,4.70,3381,Christopher Norton Patterson,Regular Air,Home Office,Office Supplies,Paper,...,Macon,31204,2013-10-09,2013-10-11,174.38400,15,69.66,88850,2 days,Sam
9422,Not Specified,0.00,58.14,36.61,3382,Jon Beasley,Delivery Truck,Corporate,Furniture,Bookcases,...,Marietta,30062,2011-05-21,2011-05-21,12.42600,13,807.21,88842,0 days,Sam
9423,Not Specified,0.00,29.99,5.50,3382,Jon Beasley,Regular Air,Corporate,Technology,Computer Peripherals,...,Marietta,30062,2011-05-21,2011-05-22,-94.55600,7,218.15,88842,1 days,Sam
9424,Not Specified,0.03,16.16,7.74,3382,Jon Beasley,Regular Air,Corporate,Furniture,Office Furnishings,...,Marietta,30062,2011-05-21,2011-05-23,-5257.04634,1,20.17,88842,2 days,Sam
9425,Not Specified,0.04,5.98,7.15,3382,Jon Beasley,Regular Air,Corporate,Office Supplies,Paper,...,Marietta,30062,2013-10-07,2013-10-09,-85.90400,3,21.86,88849,2 days,Sam

In [29]:
pd.DataFrame(region_orders[region_orders['Order_Duration'].dt.components['days'] > 15][['Order ID','Manager']])

      Order ID  Manager
189      87215    Chris
3476     87957  William
3478     87957  William
3495     19556  William
3497     19556  William
3826     86177  William
4476     91294  William
6638     88352     Erin
7314     19841     Erin
7315     19841     Erin
7325     19841     Erin
7328     87300     Erin
7329     87300     Erin
8435     87572      Sam
9184     86434      Sam
9186     86436      Sam
9187     86436      Sam
9307     87300      Sam

### 11. Gorup by region and find out which region is more profitable.

In [30]:
pd.DataFrame(region_orders.groupby('Region')['Profit'].sum())

                Profit
Region
Central  519825.567067
East     377566.186045
South    104201.192420
West     310849.453897

### 12. Try to find out overall in which country we are giving more discount.

In [31]:
# Country is missing, let us consider State
pd.DataFrame(orders.groupby('State or Province')['Discount'].sum().sort_values(ascending=False)[0:1])

                   Discount
State or Province
California            52.28

### 13. Give me a list of unique postal code.

In [32]:
postalcode_lst = list(orders['Postal Code'].unique())
postalcode_lst

[60101,
 98221,
 91776,
 95123,
 2724,
 3110,
 8101,
 8109,
 7203,
 2907,
 55372,
 11787,
 13210,
 59405,
 59601,
 59801,
 68005,
 10012,
 92653,
 92677,
 92530,
 92630,
 90712,
 93534,
 90260,
 97405,
 97526,
 97030,
 97123,
 97303,
 62002,
 98373,
 98052,
 75019,
 23834,
 62701,
 60107,
 60477,
 14150,
 12180,
 77642,
 75080,
 77471,
 78664,
 75088,
 24153,
 94043,
 92563,
 94559,
 10177,
 2917,
 5401,
 4070,
 2331,
 8830,
 8701,
 7470,
 7481,
 5201,
 97035,
 44708,
 45231,
 44105,
 95687,
 5451,
 94591,
 70056,
 22102,
 60601,
 66209,
 66215,
 66502,
 66062,
 6510,
 4401,
 4005,
 2129,
 2038,
 1852,
 1752,
 2067,
 3820,
 8618,
 7644,
 7110,
 8861,
 7095,
 2895,
 97128,
 97504,
 98103,
 84118,
 84041,
 93277,
 76903,
 78207,
 60004,
 94952,
 1510,
 1106,
 1880,
 6401,
 6360,
 2664,
 15122,
 76148,
 5439,
 5403,
 37664,
 37918,
 37086,
 37087,
 80525,
 80817,
 60452,
 76131,
 98059,
 99352,
 37804,
 70802,
 4092,
 7024,
 76240,
 98158,
 78415,
 94122,
 4011,
 4240,
 2474,
 2540,
 1580,
 3038,
 60505,
 84043,
 84321,
 66212,
 48138,
 85335,
 74006,
 75217,
 77536,
 90660,
 13501,
 11580,
 63114,
 84044,
 84047,
 84107,
 60453,
 2021,
 2766,
 7101,
 28227,
 60302,
 60462,
 50208,
 80027,
 66203,
 81503,
 80634,
 37922,
 38109,
 55423,
 55901,
 55113,
 80126,
 80232,
 17331,
 33772,
 87505,
 12208,
 44106,
 43229,
 78589,
 86001,
 85234,
 85301,
 30297,
 28204,
 6824,
 6111,
 6226,
 7109,
 66614,
 67212,
 80538,
 80233,
 80134,
 6830,
 6770,
 6855,
 4073,
 1069,
 2725,
 21234,
 21128,
 21208,
 20854,
 98115,
 91945,
 94404,
 60130,
 1007,
 7111,
 8052,
 21133,
 60510,
 3045,
 7410,
 97045,
 97206,
 44221,
 6478,
 33181,
 4101,
 3246,
 3101,
 7010,
 2878,
 33132,
 13601,
 85338,
 86401,
 19406,
 93727,
 4072,
 7628,
 7071,
 2816,
 2910,
 2886,
 94601,
 2149,
 1840,
 48234,
 37814,
 62223,
 61008,
 61701,
 60440,
 19026,
 68025,
 68801,
 68847,
 68502,
 48509,
 63105,
 13021,
 13905,
 28001,
 45406,
 43015,
 95240,
 90805,
 4901,
 8360,
 78666,
 7026,
 93405,
 94403,
 2358,
 7201,
 7032,
 7666,
 68104,
 89701,
 94583,
 92704,
 6010,
 6108,
 4330,
 1462,
 2370,
 7047,
 7480,
 61801,
 68701,
 56301,
 94024,
 93635,
 95032,
 90266,
 1923,
 2457,
 3054,
 8332,
 90069,
 92683,
 90604,
 2019,
 1915,
 2341,
 7506,
 8601,
 30318,
 1845,
 39180,
 11704,
 11795,
 60543,
 95020,
 4106,
 2062,
 7042,
 10154,
 24281,
 37130,
 84404,
 84057,
 55416,
 46041,
 42104,
 41011,
 95336,
 4038,
 2148,
 8753,
 76067,
 11226,
 97756,
 85204,
 85737,
 84062,
 64064,
 63043,
 22025,
 60061,
 93101,
 95051,
 26501,
 88201,
 78155,
 75090,
 90008,
 68046,
 84604,
 60067,
 60068,
 60087,
 60185,
 75081,
 60187,
 60090,
 39701,
 89015,
 61554,
 61604,
 91767,
 6415,
 4210,
 2032,
 1801,
 3301,
 8021,
 7031,
 7054,
 60091,
 60517,
 46016,
 47401,
 46032,
 47201,
 21136,
 81001,
 90045,
 14224,
 10605,
 10701,
 97301,
 97477,
 97224,
 81007,
 48195,
 5701,
 43952,
 20852,
 20602,
 55106,
 55378,
 95062,
 93454,
 98119,
 60544,
 62301,
 55379,
 60089,
 89115,
 91730,
 2116,
 1540,
 77373,
 37211,
 75203,
 52501,
 64133,
 63301,
 64506,
 98387,
 99207,
 98408,
 77478,
 63116,
 63376,
 80229,
 80030,
 46307,
 46312,
 98105,
 90041,
 90405,
 95404,
 95070,
 6040,
 6460,
 6850,
 6702,
 1520,
 2152,
 7067,
 2840,
 48841,
 89031,
 89041,
 41042,
 6614,
 1803,
 1420,
 1089,
 2190,
 3053,
 3079,
 7003,
 7016,
 7039,
 8232,
 7901,
 85345,
 85023,
 60423,
 40324,
 86301,
 86314,
 97062,
 61201,
 98661,
 14215,
 61107,
 97068,
 18103,
 16602,
 72143,
 92054,
 6033,
 6484,
 6437,
 92691,
 95351,
 6512,
 7001,
 73064,
 27502,
 84067,
 29915,
 84106,
 32168,
 37830,
 42420,
 85254,
 8046,
 99362,
 37167,
 37174,
 79605,
 75002,
 79109,
 71854,
 80033,
 21222,
 6511,
 8002,
 91745,
 93117,
 6114,
 2210,
 1450,
 1060,
 3839,
 92544,
 92345,
 6405,
 6810,
 6492,
 75503,
 77590,
 46514,
 55126,
 89502,
 66202,
 11575,
 85635,
 93422,
 20746,
 76017,
 78745,
 77520,
 77705,
 76021,
 89431,
 20024,
 83616,
 76201,
 33430,
 10039,
 1887,
 7652,
 42240,
 26003,
 78521,
 77803,
 76028,
 96003,
 92374,
 1463,
 7008,
 8857,
 7050,
 7501,
 90278,
 6776,
 2127,
 1605,
 7002,
 2914,
 90049,
 75482,
 75067,
 19901,
 19711,
 94061,
 60610,
 6105,
 2108,
 3842,
 92503,
 95677,
 2339,
 1841,
 7079,
 91761,
 1718,
 1701,
 1040,
 2151,
 7650,
 93030,
 3431,
 7601,
 7450,
 11720,
 60459,
 7712,
 72022,
 28806,
 27217,
 27511,
 66762,
 55125,
 15221,
 11722,
 14225,
 11725,
 27514,
 28205,
 28027,
 27707,
 43017,
 15102,
 95695,
 95991,
 92399,
 90004,
 6473,
 2109,
 7030,
 85351,
 85374,
 3060,
 2864,
 11727,
 10573,
 60409,
 62901,
 18018,
 60441,
 60174,
 60193,
 60076,
 11729,
 11746,
 8816,
 8817,
 7646,
 65721,
 10282,
 18040,
 75220,
 77566,
 75146,
 78041,
 77573,
 80004,
 85281,
 85705,
 85364,
 72714,
 72015,
 92592,
 95661,
 75116,
 78852,
 78539,
 2118,
 79907,
 76039,
 75234,
 60188,
 75056,
 77381,
 75701,
 77901,
 76706,
 75165,
 76086,
 6611,
 1821,
 1056,
 1075,
 7801,
 90640,
 1876,
 7086,
 3801,
 7407,
 8226,
 7070,
 19805,
 32701,
 2040,
 10280,
 27237,
 84660,
 84663,
 35756,
 92646,
 90301,
 6050,
 6790,
 20016,
 34142,
 1108,
 1776,
 7843,
 2920,
 32712,
 46806,
 46404,
 46530,
 97420,
 19013,
 2112,
 1906,
 2451,
 7052,
 2861,
 19140,
 98801,
 75028,
 76106,
 75007,
 75104,
 78613,
 36830,
 35020,
 78641,
 10009,
 75057,
 60110,
 61821,
 77530,
 76031,
 80013,
 80303,
 40422,
 80020,
 80104,
 80906,
 73521,
 33433,
 33437,
 34210,
 91941,
 1930,
 8401,
 7097,
 46142,
 46324,
 47591,
 19134,
 15241,
 6320,
 47274,
 1749,
 2153,
 33180,
 75601,
 84074,
 98902,
 25314,
 82604,
 84084,
 84120,
 60623,
 11554,
 90058,
 80022,
 80219,
 77840,
 2478,
 1453,
 2744,
 8302,
 8028,
 7940,
 62234,
 10170,
 17201,
 77546,
 33511,
 33063,
 33055,
 78596,
 76308,
 52761,
 48101,
 32707,
 79424,
 75901,
 76063,
 75098,
 95207,
 6408,
 2703,
 1832,
 22304,
 46342,
 46203,
 94025,
 94086,
 91360,
 1027,
 1867,
 8863,
 60653,
 48104,
 49017,
 48708,
 84003,
 92553,
 95037,
 2113,
 47130,
 46901,
 47905,
 28031,
 44112,
 80112,
 21146,
 20901,
 44035,
 44117,
 65807,
 63130,
 63135,
 16509,
 17112,
 96150,
 6795,
 2638,
 8901,
 97801,
 29687,
 46226,
 46952,
 46410,
 68601,
 84010,
 84015,
 43081,
 44145,
 44691,
 82001,
 82716,
 33134,
 53110,
 60016,
 60516,
 46360,
 10045,
 94044,
 32137,
 59901,
 14901,
 33065,
 60478,
 46544,
 47302,
 47150,
 62205,
 6488,
 6710,
 1545,
 2072,
 55305,
 35211,
 35601,
 27288,
 92262,
 63385,
 92253,
 78363,
 33314,
 32114,
 46060,
 46368,
 47374,
 39530,
 39056,
 38701,
 39503,
 22003,
 22204,
 24060,
 78501,
 75150,
 33441,
 32720,
 60123,
 45385,
 28314,
 28307,
 6607,
 77571,
 63044,
 44094,
 44511,
 25705,
 82070,
 68901,
 20601,
 11598,
 11010,
 11520,
 95823,
 93905,
 2445,
 1748,
 45324,
 46322,
 97601,
 17602,
 46375,
 11542,
 10528,
 37743,
 74012,
 77095,
 39401,
 38637,
 39212,
 92404,
 94070,
 6901,
 11714,
 60098,
 27203,
 98072,
 90503,
 15131,
 33403,
 33445,
 22015,
 22901,
 23320,
 67114,
 25801,
 45014,
 45840,
 60611,
 77301,
 60007,
 20190,
 72701,
 72903,
 71901,
 19057,
 39301,
 44118,
 19464,
 30062,
 30907,
 30265,
 49534,
 27529,
 35473,
 72401,
 72209,
 92037,
 43026,
 45424,
 44240,
 45429,
 83843,
 88310,
 20012,
 11550,
 28052,
 27534,
 27405,
 27834,
 75034,
 30305,
 73034,
 73703,
 73505,
 73110,
 90036,
 79701,
 95376,
 1607,
 32725,
 34698,
 63141,
 60126,
 60201,
 61032,
 32780,
 46614,
 47802,
 46383,
 47906,
 50010,
 92672,
 92105,
 1945,
 30188,
 59102,
 61401,
 60137,
 94110,
 50021,
 52722,
 63119,
 26101,
 36330,
 90032,
 38654,
 39208,
 48187,
 49236,
 48126,
 48127,
 33178,
 11801,
 52601,
 50613,
 52402,
 15146,
 38671,
 1810,
 2334,
 1469,
 43230,
 1886,
 11741,
 35630,
 92008,
 6443,
 2110,
 1826,
 2035,
 2169,
 1550,
 1570,
 7080,
 7090,
 2808,
 87105,
 94306,
 22193,
 24541,
 ...]

### 14. Which customer segement is more profitalble find it out.

In [33]:
pd.DataFrame(orders.groupby('Customer Segment')['Profit'].sum())

                         Profit
Customer Segment
Consumer          206559.625348
Corporate         505538.627783
Home Office       283869.553814
Small Business    316474.592482

### 15. Try to find out the 10th most loss making product category.

In [34]:
orders[orders['Profit'] < 0].groupby('Product Category')['Profit'].sum()

# There are only 3 categories

Product Category
Furniture         -410464.845289
Office Supplies   -393433.301145
Technology        -358842.689349
Name: Profit, dtype: float64

In [35]:
# As there are only 3 categories considering subcategories
m = orders[orders['Profit'] < 0].groupby('Product Sub-Category')['Profit'].sum().sort_values(ascending=True)
pd.DataFrame(m)

                                       Profit
Product Sub-Category
Office Machines                -173795.361944
Tables                         -169903.535991
Storage & Organization         -114982.468893
Chairs & Chairmats              -91324.125160
Telephones and Communication    -90157.260448
Paper                           -81736.283532
Bookcases                       -78874.273384
Binders and Binder Accessories  -71125.435385
Office Furnishings              -70362.910753
Computer Peripherals            -56544.485587
Appliances                      -51157.637560
Pens & Art Supplies             -39737.237980
Copiers and Fax                 -38345.581370
Scissors, Rulers and Trimmers   -11056.338300
Envelopes                        -9127.009240
Rubber Bands                     -7753.018599
Labels                           -6757.871655

In [36]:
pd.DataFrame(m[[9]])

                            Profit
Product Sub-Category
Computer Peripherals -56544.485587

### 16. Try to find out 10 top product with highest margins.

In [37]:
orders.groupby(['Product Base Margin','Product Name']).sum().sort_values(['Product Base Margin'])[0:10]

                                                                        Discount  \
Product Base Margin Product Name
0.35                "While you Were Out" Message Book, One Form per...      0.47
                    Prang Dustless Chalk Sticks                             0.31
                    Presstex Flexible Ring Binders                          0.43
                    REDIFORM Incoming/Outgoing Call Register, 11" X...      0.21
                    Recycled Interoffice Envelopes with String and ...      0.32
                    Sharp 1540cs Digital Laser Copier                       0.08
                    Southworth Structures Collection™                       0.35
                    Staples #10 Laser & Inkjet Envelopes, 4 1/8" x ...      0.32
                    Peel & Seel® Recycled Catalog Envelopes, Brown          1.03
                    Staples Brown Kraft Recycled Clasp Envelopes            0.50

                                                                        Unit Price  \
Product Base Margin Product Name
0.35                "While you Were Out" Message Book, One Form per...       22.26
                    Prang Dustless Chalk Sticks                               8.40
                    Presstex Flexible Ring Binders                           40.95
                    REDIFORM Incoming/Outgoing Call Register, 11" X...       41.70
                    Recycled Interoffice Envelopes with String and ...      143.94
                    Sharp 1540cs Digital Laser Copier                      1649.97
                    Southworth Structures Collection™                        29.12
                    Staples #10 Laser & Inkjet Envelopes, 4 1/8" x ...       48.90
                    Peel & Seel® Recycled Catalog Envelopes, Brown          254.76
                    Staples Brown Kraft Recycled Clasp Envelopes             78.12

                                                                        Shipping Cost  \
Product Base Margin Product Name
0.35                "While you Were Out" Message Book, One Form per...          11.58
                    Prang Dustless Chalk Sticks                                  5.00
                    Presstex Flexible Ring Binders                              13.41
                    REDIFORM Incoming/Outgoing Call Register, 11" X...           7.15
                    Recycled Interoffice Envelopes with String and ...          40.26
                    Sharp 1540cs Digital Laser Copier                          147.00
                    Southworth Structures Collection™                           21.88
                    Staples #10 Laser & Inkjet Envelopes, 4 1/8" x ...          28.80
                    Peel & Seel® Recycled Catalog Envelopes, Brown             143.34
                    Staples Brown Kraft Recycled Clasp Envelopes                74.20

                                                                        Customer ID  \
Product Base Margin Product Name
0.35                "While you Were Out" Message Book, One Form per...         5319
                    Prang Dustless Chalk Sticks                               11124
                    Presstex Flexible Ring Binders                            19060
                    REDIFORM Incoming/Outgoing Call Register, 11" X...         7203
                    Recycled Interoffice Envelopes with String and ...        14179
                    Sharp 1540cs Digital Laser Copier                          3902
                    Southworth Structures Collection™                          9399
                    Staples #10 Laser & Inkjet Envelopes, 4 1/8" x ...         9387
                    Peel & Seel® Recycled Catalog Envelopes, Brown            31184
                    Staples Brown Kraft Recycled Clasp Envelopes              20958

                                                                        Postal Code  \
Product Base Margin Product Name
0.35                "While you Were Out" Message Book, One Form per...       434824
                    Prang Dustless Chalk Sticks                              168212
                    Presstex Flexible Ring Binders                           530292
                    REDIFORM Incoming/Outgoing Call Register, 11" X...       299757
                    Recycled Interoffice Envelopes with String and ...       409059
                    Sharp 1540cs Digital Laser Copier                        206262
                    Southworth Structures Collection™                        295912
                    Staples #10 Laser & Inkjet Envelopes, 4 1/8" x ...       289550
                    Peel & Seel® Recycled Catalog Envelopes, Brown          1283299
                    Staples Brown Kraft Recycled Clasp Envelopes             841121

                                                                             Profit  \
Product Base Margin Product Name
0.35                "While you Were Out" Message Book, One Form per...   708.820800
                    Prang Dustless Chalk Sticks                        -1320.103200
                    Presstex Flexible Ring Binders                       306.691704
                    REDIFORM Incoming/Outgoing Call Register, 11" X...    57.366300
                    Recycled Interoffice Envelopes with String and ...   784.815900
                    Sharp 1540cs Digital Laser Copier                   3381.787600
                    Southworth Structures Collection™                   -388.078712
                    Staples #10 Laser & Inkjet Envelopes, 4 1/8" x ...   648.744080
                    Peel & Seel® Recycled Catalog Envelopes, Brown      -306.805920
                    Staples Brown Kraft Recycled Clasp Envelopes        -456.499860

                                                                        Quantity ordered new  \
Product Base Margin Product Name
0.35                "While you Were Out" Message Book, One Form per...                    70
                    Prang Dustless Chalk Sticks                                           69
                    Presstex Flexible Ring Binders                                       107
                    REDIFORM Incoming/Outgoing Call Register, 11" X...                   142
                    Recycled Interoffice Envelopes with String and ...                    73
                    Sharp 1540cs Digital Laser Copier                                     35
                    Southworth Structures Collection™                                     31
                    Staples #10 Laser & Inkjet Envelopes, 4 1/8" x ...                    28
                    Peel & Seel® Recycled Catalog Envelopes, Brown                       329
                    Staples Brown Kraft Recycled Clasp Envelopes                         174

                                                                           Sales  \
Product Base Margin Product Name
0.35                "While you Were Out" Message Book, One Form per...    259.31
                    Prang Dustless Chalk Sticks                           115.20
                    Presstex Flexible Ring Binders                        483.91
                    REDIFORM Incoming/Outgoing Call Register, 11" X...   1188.86
                    Recycled Interoffice Envelopes with String and ...   1738.32
                    Sharp 1540cs Digital Laser Copier                   18829.68
                    Southworth Structures Collection™                     221.14
                    Staples #10 Laser & Inkjet Envelopes, 4 1/8" x ...    283.56
                    Peel & Seel® Recycled Catalog Envelopes, Brown       3832.55
                    Staples Brown Kraft Recycled Clasp Envelopes         1027.92

                                                                        Order ID
Product Base Margin Product Name
0.35                "While you Were Out" Message Book, One Form per...    502011
                    Prang Dustless Chalk Sticks                           446810
                    Presstex Flexible Ring Binders                        747298
                    REDIFORM Incoming/Outgoing Call Register, 11" X...    295744
                    Recycled Interoffice Envelopes with String and ...    528916
                    Sharp 1540cs Digital Laser Copier                     267082
                    Southworth Structures Collection™                     355889
                    Staples #10 Laser & Inkjet Envelopes, 4 1/8" x ...    444688
                    Peel & Seel® Recycled Catalog Envelopes, Brown       1820343
                    Staples Brown Kraft Recycled Clasp Envelopes          996162

</br></br></br></br></br>

submit your git link for the same 
 
you have to submit this task by next Friday 5th 11PM IST  to respective mail id 
sudhanshu@ineuron.ai , sunny.savita@ineuron.ai