In [18]:
import pandas as pd

In [19]:
df= pd.read_excel('pokemon_data.xlsx')
df

,Unnamed: 0,id,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,0,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,1,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,2,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,NaN,"['Fire', 'Ice', 'Flying', 'Psychic']",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,3,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"['Water', 'Ground', 'Rock']","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,4,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"['Water', 'Ground', 'Rock']","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,146,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,['Dragon'],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.8399999999999999]","['Ice', 'Dragon', 'Fairy']","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN
147,147,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,['Dragon'],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"['Ice', 'Dragon', 'Fairy']","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]"
148,148,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"['Dragon', 'Flying']",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,NaN,"['Ice', 'Rock', 'Dragon', 'Fairy']",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1..."
149,149,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,NaN,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN
150,150,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,NaN,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN

### 1. Pokemons whose spawn rate is less than 5%

In [20]:
five_perc = df["spawn_chance"].quantile(0.05)
df[df["spawn_chance"] < five_perc]["name"]

131        Ditto
143     Articuno
144       Zapdos
145      Moltres
148    Dragonite
149       Mewtwo
150          Mew
Name: name, dtype: object

### 2. Pokemons that have less than 4 weaknesses

In [23]:
(df.weaknesses[0])

['Fire', 'Ice', 'Flying', 'Psychic']

In [22]:
df["weaknesses"]= df["weaknesses"].apply(eval)

In [24]:
def weaknesses_count(wek):
    return len(wek)

df['weaknesses_count']= df["weaknesses"].apply(weaknesses_count)
df

,Unnamed: 0,id,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,weaknesses_count
0,0,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,4
1,1,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",4
2,2,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,NaN,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",4
3,3,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,3
4,4,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,146,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,['Dragon'],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.8399999999999999]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN,3
147,147,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,['Dragon'],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]",3
148,148,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"['Dragon', 'Flying']",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,NaN,"[Ice, Rock, Dragon, Fairy]",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1...",4
149,149,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,NaN,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Bug, Ghost, Dark]",NaN,NaN,3
150,150,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,NaN,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Bug, Ghost, Dark]",NaN,NaN,3

In [26]:
df[df['weaknesses_count']<4].name

3      Charmander
4      Charmeleon
5       Charizard
6        Squirtle
7       Wartortle
          ...
145       Moltres
146       Dratini
147     Dragonair
149        Mewtwo
150           Mew
Name: name, Length: 102, dtype: object

### 3. Pokemons that have no multipliers at all

In [27]:
df[df["multipliers"].isna()]["name"]

2        Venusaur
5       Charizard
8       Blastoise
11     Butterfree
14       Beedrill
          ...
144        Zapdos
145       Moltres
148     Dragonite
149        Mewtwo
150           Mew
Name: name, Length: 81, dtype: object

### 4. Pokemons that do not have more than 2 evolutions

In [29]:
df1 = df.copy()

In [30]:
df1['next_evolution'].dropna(inplace= True)

In [31]:
import ast

In [32]:
df1["Evloutions_2"] = df1["next_evolution"].dropna().apply(lambda x : ast.literal_eval(x)).apply(lambda x : len(x)) < 2

In [33]:
df1.loc[df1["Evloutions_2"] == True]["name"]

1         Ivysaur
4      Charmeleon
7       Wartortle
10        Metapod
13         Kakuna
16      Pidgeotto
18        Rattata
20        Spearow
22          Ekans
24        Pikachu
26      Sandshrew
29       Nidorina
32       Nidorino
34       Clefairy
36         Vulpix
38     Jigglypuff
40          Zubat
43          Gloom
45          Paras
47        Venonat
49        Diglett
51         Meowth
53        Psyduck
55         Mankey
57      Growlithe
60      Poliwhirl
63        Kadabra
66        Machoke
69     Weepinbell
71      Tentacool
74       Graveler
76         Ponyta
78       Slowpoke
80      Magnemite
83          Doduo
85           Seel
87         Grimer
89       Shellder
92        Haunter
95        Drowzee
97         Krabby
99        Voltorb
101     Exeggcute
103        Cubone
108       Koffing
110       Rhyhorn
115        Horsea
117       Goldeen
119        Staryu
128      Magikarp
137       Omanyte
139        Kabuto
147     Dragonair
Name: name, dtype: object

### 5. Pokemons whose spawn time is less than 300 seconds

In [34]:
df1["spawn_time_less_then_300"] = df1["spawn_time"].dropna().apply(lambda x: (int(x.split(":")[0]) * 60) +(int(x.split(":")[1]))) < 300

In [35]:
df1.loc[df1["spawn_time_less_then_300"] == True]["name"]

6       Squirtle
8      Blastoise
10       Metapod
12        Weedle
13        Kakuna
         ...
127       Tauros
129     Gyarados
134      Jolteon
136      Porygon
139       Kabuto
Name: name, Length: 75, dtype: object

### 6. Pokemon who have more than two types of capabilities

In [36]:
df1["type"] = df1["type"].apply(lambda x : ast.literal_eval(x))

In [37]:
df1[df1["type"].apply(lambda x : len(x) > 2)]["name"]
#There are no pokemon more than two types of capabilities

Series([], Name: name, dtype: object)